version: "1"
project:
  name: crispy-tivi
  languages:
    - dart
    - rust
    - json
    - typescript
    - markdown
    - yaml
    - swift
    - c++
    - xml
    - c header
    - kotlin
    - cmake
    - xcode config
    - toml
    - gradle
    - plain text
    - glsl
    - javascript
    - properties file
    - bash
    - html
    - makefile
    - svg
    - shell
    - windows resource-definition script
  topology: monolith
  architecture: none
scanners:
  semgrep:
    enabled: true
    rulesets:
      - p/default
  trivy:
    enabled: true
    scanners:
      - vuln
      - secret
  ast-grep:
    enabled: false
    rules: ""
  gitleaks:
    enabled: true
  jscpd:
    enabled: true
    threshold: 10
  scc:
    enabled: true
  sonarqube:
    enabled: false
    host: ""
fixers:
  formatters: true
  linters: true
  security: true
  ast: false
  deps: true
  unsafe: false
filters:
  include: []
  exclude:
    - vendor/
    - node_modules/
    - target/
    - .git/
    - "*.generated.*"
    - dist/
tools:
  scanners:
    semgrep: true
    gitleaks: true
    scc: true
    jscpd: true
    trivy: true
  fixers:
    typescript:
      prettier: false
      biome-format: false
      biome-lint-safe: false
      eslint-safe: false
      npm-audit-fix-force: true
      biome-imports: false
      npm-audit-fix: true
      eslint-unsafe: false
    dart:
      dart-fix: true
      dart-format: true
      flutter-analyze: true
      dart-pub-upgrade: true
      dart-fix-imports: true
    shell:
      shellcheck-safe: false
      shellcheck-unsafe: false
      shfmt: false
    rust:
      cargo-fix-unused: true
      clippy-unsafe: true
      cargo-update: true
      clippy-safe: true
      rustfmt: true
    kotlin:
      gradle-kotlin-deps: false
      detekt-unsafe: false
      ktfmt: false
      semgrep-kotlin-security: true
      detekt-safe: false
    javascript:
      biome-imports: false
      biome-lint-safe: false
      eslint-safe: false
      eslint-unsafe: false
      prettier: false
      biome-format: false
      npm-audit-fix: true
output:
  format: json
  severity_threshold: warning
  include_evidence: true
hooks:
  pre-commit:
    enabled: false
    manager: ""
    checks: []
ci:
  provider: none
  diff_only: true
