import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/theme/crispy_animation.dart';
import '../../../../core/theme/crispy_radius.dart';
import '../../../../core/theme/crispy_spacing.dart';

import '../../domain/entities/commercial_marker.dart';
import '../providers/dvr_providers.dart';

// ── State ─────────────────────────────────────────────────────────

/// Immutable state for the commercial-skip system.
class CommercialSkipState {
  const CommercialSkipState({
    this.markers = const [],
    this.currentPositionMs = 0,
    this.activeMarker,
  });

  /// Full list of detected commercial markers for the current recording.
  final List<CommercialMarker> markers;

  /// Current playback position in milliseconds.
  ///
  /// Updated by [CommercialSkipNotifier.updatePosition].
  final int currentPositionMs;

  /// The marker the player is currently inside, or null if none.
  final CommercialMarker? activeMarker;

  /// Whether the player is currently inside a commercial break.
  bool get isInCommercial => activeMarker != null;

  CommercialSkipState copyWith({
    List<CommercialMarker>? markers,
    int? currentPositionMs,
    CommercialMarker? activeMarker,
    bool clearActiveMarker = false,
  }) {
    return CommercialSkipState(
      markers: markers ?? this.markers,
      currentPositionMs: currentPositionMs ?? this.currentPositionMs,
      activeMarker:
          clearActiveMarker ? null : (activeMarker ?? this.activeMarker),
    );
  }
}

// ── Notifier ──────────────────────────────────────────────────────

/// Manages commercial marker detection and playback position tracking.
class CommercialSkipNotifier extends Notifier<CommercialSkipState> {
  @override
  CommercialSkipState build() => const CommercialSkipState();

  /// Load markers for the recording being played.
  ///
  /// Fetches markers generated by the Rust backend.
  Future<void> loadMarkers(String recordingId) async {
    try {
      final cache = ref.read(cacheServiceProvider);
      final markers = await cache.getRecordingMarkers(recordingId);
      state = state.copyWith(markers: markers);
    } catch (e) {
      debugPrint('Failed to load commercial markers: $e');
      state = const CommercialSkipState();
    }
  }

  /// Update the current playback position and re-derive [activeMarker].
  ///
  /// Call this on every player position tick (e.g. from a
  /// position stream or timer). Triggers UI to show/hide the
  /// "Skip Ad" button.
  void updatePosition(int positionMs) {
    final marker = _findActiveMarker(positionMs);
    state = state.copyWith(
      currentPositionMs: positionMs,
      activeMarker: marker,
      clearActiveMarker: marker == null,
    );
  }

  /// Clear all markers (e.g. when the player stops).
  void clear() {
    state = const CommercialSkipState();
  }

  /// Returns the marker that contains [positionMs], or null.
  CommercialMarker? _findActiveMarker(int positionMs) {
    for (final marker in state.markers) {
      if (positionMs >= marker.startMs && positionMs < marker.endMs) {
        return marker;
      }
    }
    return null;
  }
}

/// Global commercial-skip provider.
final commercialSkipProvider =
    NotifierProvider<CommercialSkipNotifier, CommercialSkipState>(
      CommercialSkipNotifier.new,
    );

// ── Widget ────────────────────────────────────────────────────────

/// Overlay widget that shows a "Skip Ad" button during commercial breaks.
///
/// Place this in the player OSD stack, above the video surface but
/// below other OSD controls. It is a no-op when no active commercial
/// marker is detected.
///
/// ```dart
/// Stack(
///   children: [
///     VideoPlayer(…),
///     CommercialSkipOverlay(
///       onSkip: () {
///         // Seek player to marker.endMs.
///         playerController.seekTo(Duration(milliseconds: markerEndMs));
///       },
///     ),
///     OsdControls(…),
///   ],
/// )
/// ```
class CommercialSkipOverlay extends ConsumerStatefulWidget {
  const CommercialSkipOverlay({super.key, required this.onSkip});

  /// Called when the user taps "Skip Ad". Callers should seek the player
  /// to [CommercialSkipState.activeMarker?.endMs].
  final VoidCallback onSkip;

  @override
  ConsumerState<CommercialSkipOverlay> createState() =>
      _CommercialSkipOverlayState();
}

class _CommercialSkipOverlayState extends ConsumerState<CommercialSkipOverlay> {
  Timer? _countdownTimer;
  int _countdownSeconds = 0;

  @override
  void dispose() {
    _countdownTimer?.cancel();
    super.dispose();
  }

  void _startCountdown(CommercialMarker marker) {
    _countdownTimer?.cancel();
    final remainingMs =
        marker.endMs - ref.read(commercialSkipProvider).currentPositionMs;
    _countdownSeconds = (remainingMs / 1000).ceil().clamp(0, 9999);

    _countdownTimer = Timer.periodic(const Duration(seconds: 1), (t) {
      if (!mounted) {
        t.cancel();
        return;
      }
      setState(() {
        if (_countdownSeconds > 0) {
          _countdownSeconds--;
        } else {
          t.cancel();
        }
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    final skipState = ref.watch(commercialSkipProvider);
    final marker = skipState.activeMarker;

    if (marker == null) {
      _countdownTimer?.cancel();
      return const SizedBox.shrink();
    }

    // Start countdown when entering a new commercial break.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_countdownTimer == null || !_countdownTimer!.isActive) {
        _startCountdown(marker);
      }
    });

    return Positioned(
      right: CrispySpacing.lg,
      bottom: CrispySpacing.xxl,
      child: _SkipAdButton(
        countdownSeconds: _countdownSeconds,
        onSkip: () {
          _countdownTimer?.cancel();
          widget.onSkip();
        },
      ),
    );
  }
}

/// The "Skip Ad" button with countdown badge.
class _SkipAdButton extends StatelessWidget {
  const _SkipAdButton({required this.countdownSeconds, required this.onSkip});

  final int countdownSeconds;
  final VoidCallback onSkip;

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;

    return AnimatedScale(
      scale: 1.0,
      duration: CrispyAnimation.fast,
      curve: CrispyAnimation.enterCurve,
      child: FilledButton.icon(
        style: FilledButton.styleFrom(
          backgroundColor: cs.primaryContainer,
          foregroundColor: cs.onPrimaryContainer,
          padding: const EdgeInsets.symmetric(
            horizontal: CrispySpacing.md,
            vertical: CrispySpacing.sm,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(CrispyRadius.tv),
          ),
        ),
        onPressed: onSkip,
        icon: const Icon(Icons.skip_next, size: 20),
        label: Text(
          countdownSeconds > 0 ? 'Skip Ad ($countdownSeconds)' : 'Skip Ad',
          style: Theme.of(context).textTheme.labelLarge?.copyWith(
            color: cs.onPrimaryContainer,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
    );
  }
}
