// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String sourceRegistryJson() =>
    RustLib.instance.api.crateApiSourceRegistryJson();

String updateSourceSetupJson({
  required String sourceRegistryJson,
  required String action,
  String? selectedProviderType,
  int? selectedSourceIndex,
  String? targetStep,
  String? fieldKey,
  String? fieldValue,
}) => RustLib.instance.api.crateApiUpdateSourceSetupJson(
  sourceRegistryJson: sourceRegistryJson,
  action: action,
  selectedProviderType: selectedProviderType,
  selectedSourceIndex: selectedSourceIndex,
  targetStep: targetStep,
  fieldKey: fieldKey,
  fieldValue: fieldValue,
);

String hydrateRuntimeBundleJson({String? sourceRegistryJson}) => RustLib
    .instance
    .api
    .crateApiHydrateRuntimeBundleJson(sourceRegistryJson: sourceRegistryJson);

String playbackRuntimeJson({String? sourceRegistryJson}) => RustLib.instance
    .api
    .crateApiPlaybackRuntimeJson(sourceRegistryJson: sourceRegistryJson);

String playbackSessionRuntimeJsonFromStreamJson({
  required String playbackStreamJson,
  int? sourceIndex,
  int? qualityIndex,
  int? audioIndex,
  int? subtitleIndex,
}) => RustLib.instance.api.crateApiPlaybackSessionRuntimeJsonFromStreamJson(
  playbackStreamJson: playbackStreamJson,
  sourceIndex: sourceIndex,
  qualityIndex: qualityIndex,
  audioIndex: audioIndex,
  subtitleIndex: subtitleIndex,
);

String commitSourceSetupJson({required String sourceRegistryJson}) => RustLib
    .instance
    .api
    .crateApiCommitSourceSetupJson(sourceRegistryJson: sourceRegistryJson);

String diagnosticsRuntimeJson() =>
    RustLib.instance.api.crateApiDiagnosticsRuntimeJson();
