name: crispy_tivi
description: >
  A convergent cross-platform media streaming application
  supporting IPTV, Jellyfin, Emby, and Plex.
publish_to: "none"
version: 0.1.0-alpha

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  collection: ^1.19.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/config/
    - assets/mocks/
    - assets/shaders/
    - assets/logo.svg
    - assets/logo.png
