//! DVR recording algorithms ported from Dart.
//!
//! Ports logic from `dvr_service.dart`: recurring
//! recording expansion, conflict detection, filename
//! sanitization, and scheduled-recording discovery.

use chrono::{NaiveDate, NaiveDateTime, Timelike};
use serde::{Deserialize, Serialize};

mod filename;
mod scheduling;
mod storage;

pub use filename::{RE_SANITIZE, sanitize_filename};
pub use scheduling::{
    detect_recording_conflict, expand_recurring_recordings, find_recordings_to_start,
    get_recordings_to_start,
};
pub use storage::{
    classify_file_type, compute_storage_breakdown, filter_recordings, sort_remote_files,
};

/// A concrete recording instance generated by expanding
/// a recurring recording pattern.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordingInstance {
    /// Channel display name.
    pub channel_name: String,
    /// Programme name.
    pub program_name: String,
    /// Instance start time.
    pub start_time: NaiveDateTime,
    /// Instance end time.
    pub end_time: NaiveDateTime,
    /// Channel ID.
    pub channel_id: Option<String>,
    /// Channel logo URL.
    pub channel_logo_url: Option<String>,
    /// Stream URL for the recording source.
    pub stream_url: Option<String>,
    /// Profile that owns this recording.
    pub owner_profile_id: Option<String>,
    /// Whether shared with all profiles.
    pub is_shared: bool,
}

/// Combine a date with the time-of-day from a
/// `NaiveDateTime`.
pub(super) fn combine_date_time(date: NaiveDate, time_source: NaiveDateTime) -> NaiveDateTime {
    date.and_hms_opt(
        time_source.time().hour(),
        time_source.time().minute(),
        time_source.time().second(),
    )
    .expect("valid HMS from existing NaiveDateTime")
}
