import { Theme } from "../globals/theme.slint";
import { ComboBox } from "std-widgets.slint";

export component Dropdown inherits VerticalLayout {
  in property <string> label;
  in property <[string]> model;
  in-out property <int> current-index <=> combo.current-index;
  in-out property <string> current-value <=> combo.current-value;

  callback selected(string);

  spacing: 6px;

  Text {
    text: root.label;
    color: Theme.text-secondary;
    font-size: 13px;
    font-family: Theme.font-body;
  }

  combo := ComboBox {
    model: root.model;
    height: 48px;

    selected(val) => { root.selected(val); }
  }
}
