// <auto-generated />
using System;

using Crispy.Infrastructure.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Crispy.Infrastructure.Data.Migrations.EpgDb;

[DbContext(typeof(EpgDbContext))]
partial class EpgDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("Crispy.Domain.Entities.EpgProgramme", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("ChannelId").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Credits").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("Description").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<string>("EpisodeNumOnScreen").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("EpisodeNumXmltvNs").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("IconUrl").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("MultiLangTitles").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<bool>("PreviouslyShown").HasColumnType("INTEGER");
            b.Property<string>("Rating").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("StartUtc").HasColumnType("TEXT");
            b.Property<string>("StarRating").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("StopUtc").HasColumnType("TEXT");
            b.Property<string>("SubTitle").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("ChannelId", "StartUtc", "StopUtc");
            b.HasIndex("StartUtc");
            b.ToTable("Programmes");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.EpgReminder", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int>("EpgProgrammeId").HasColumnType("INTEGER");
            b.Property<bool>("IsFired").HasColumnType("INTEGER");
            b.Property<int>("ProfileId").HasColumnType("INTEGER");
            b.Property<int>("ReminderMinutesBefore").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("IsFired");
            b.HasIndex("ProfileId", "EpgProgrammeId").IsUnique();
            b.ToTable("Reminders");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.EpgReminder", b =>
        {
            b.HasOne("Crispy.Domain.Entities.EpgProgramme", "EpgProgramme")
                .WithMany()
                .HasForeignKey("EpgProgrammeId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("EpgProgramme");
        });
#pragma warning restore 612, 618
    }
}
