// <auto-generated />
using System;

using Crispy.Infrastructure.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crispy.Infrastructure.Data.Migrations.AppDb;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("Crispy.Domain.Entities.Channel", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("CatchupSource").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("CatchupType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<int>("CatchupDays").HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<int?>("CustomSortOrder").HasColumnType("INTEGER");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int?>("DeduplicationGroupId").HasColumnType("INTEGER");
            b.Property<string>("ExternalId").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("GroupName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<bool>("IsFavorite").HasColumnType("INTEGER");
            b.Property<bool>("IsHidden").HasColumnType("INTEGER");
            b.Property<bool>("IsRadio").HasColumnType("INTEGER");
            b.Property<int>("MissedSyncCount").HasColumnType("INTEGER");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("TvgChno").HasColumnType("TEXT");
            b.Property<string>("TvgId").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("TvgLogo").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("TvgName").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<int?>("UnifiedNumber").HasColumnType("INTEGER");
            b.Property<int?>("UserAssignedNumber").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("DeduplicationGroupId");
            b.HasIndex("SourceId");
            b.HasIndex("ExternalId", "SourceId").IsUnique();
            b.HasIndex("TvgId", "SourceId");
            b.ToTable("Channels");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.ChannelGroup", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.Property<int?>("SourceId").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("SourceId");
            b.HasIndex("SortOrder");
            b.ToTable("ChannelGroups");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.ChannelGroupMembership", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("ChannelGroupId").HasColumnType("INTEGER");
            b.Property<int>("ChannelId").HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("ChannelGroupId");
            b.HasIndex("ChannelId", "ChannelGroupId").IsUnique();
            b.ToTable("ChannelGroupMemberships");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.DeduplicationGroup", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("CanonicalTitle").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("CanonicalTvgId").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("DeduplicationGroups");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Download", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("ContentId").HasColumnType("INTEGER");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("FilePath").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<double>("Progress").HasColumnType("REAL");
            b.Property<string>("Quality").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<long>("SizeBytes").HasColumnType("INTEGER");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("ContentType", "ContentId");
            b.HasIndex("Status");
            b.ToTable("Downloads");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Episode", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime?>("AiredAt").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int>("EpisodeNumber").HasColumnType("INTEGER");
            b.Property<string>("Overview").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<int?>("RuntimeMinutes").HasColumnType("INTEGER");
            b.Property<int>("SeasonNumber").HasColumnType("INTEGER");
            b.Property<int>("SeriesId").HasColumnType("INTEGER");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<string>("StreamUrl").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Thumbnail").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("SourceId");
            b.HasIndex("SeriesId", "SeasonNumber", "EpisodeNumber");
            b.ToTable("Episodes");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Movie", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("BackdropUrl").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("Genres").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("Overview").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<double?>("Rating").HasColumnType("REAL");
            b.Property<int?>("RuntimeMinutes").HasColumnType("INTEGER");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<string>("StreamUrl").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Thumbnail").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<int?>("TmdbId").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.Property<int?>("Year").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("SourceId");
            b.HasIndex("TmdbId");
            b.ToTable("Movies");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Profile", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("AvatarPath").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<bool>("IsDefault").HasColumnType("INTEGER");
            b.Property<string>("PinHash").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("Profiles");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Series", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("BackdropUrl").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int?>("FirstAiredYear").HasColumnType("INTEGER");
            b.Property<string>("Genres").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("Overview").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<double?>("Rating").HasColumnType("REAL");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<string>("Thumbnail").HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<int?>("TmdbId").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("SourceId");
            b.HasIndex("TmdbId");
            b.ToTable("SeriesItems");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Setting", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<int?>("ProfileId").HasColumnType("INTEGER");
            b.Property<string>("Value").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("Settings");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Source", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<bool>("IsEnabled").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Password").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<int>("ProfileId").HasColumnType("INTEGER");
            b.Property<int>("SortOrder").HasColumnType("INTEGER");
            b.Property<string>("SourceType").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<string>("Username").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("Sources");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.StreamEndpoint", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("ChannelId").HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<int>("FailureCount").HasColumnType("INTEGER");
            b.Property<string>("Format").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<string>("HttpHeaders").HasMaxLength(4000).HasColumnType("TEXT");
            b.Property<DateTimeOffset?>("LastSuccessAt").HasColumnType("TEXT");
            b.Property<int>("Priority").HasColumnType("INTEGER");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("ChannelId", "SourceId");
            b.HasIndex("Priority");
            b.ToTable("StreamEndpoints");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.SyncHistory", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("ChannelCount").HasColumnType("INTEGER");
            b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<long>("DurationMs").HasColumnType("INTEGER");
            b.Property<int>("EpgCount").HasColumnType("INTEGER");
            b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("TEXT");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<DateTime>("StartedAt").HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.Property<int>("VodCount").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("SourceId", "StartedAt");
            b.ToTable("SyncHistory");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.WatchHistory", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("ContentId").HasColumnType("INTEGER");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<DateTime?>("DeletedAt").HasColumnType("TEXT");
            b.Property<double>("CompletionPct").HasColumnType("REAL");
            b.Property<long>("DurationMs").HasColumnType("INTEGER");
            b.Property<long>("PositionMs").HasColumnType("INTEGER");
            b.Property<int>("ProfileId").HasColumnType("INTEGER");
            b.Property<int>("SourceId").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.Property<DateTime>("WatchedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("ProfileId", "ContentType", "ContentId");
            b.HasIndex("WatchedAt");
            b.ToTable("WatchHistory");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Channel", b =>
        {
            b.HasOne("Crispy.Domain.Entities.DeduplicationGroup", "DeduplicationGroup")
                .WithMany("Channels")
                .HasForeignKey("DeduplicationGroupId")
                .OnDelete(DeleteBehavior.SetNull);
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("DeduplicationGroup");
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.ChannelGroupMembership", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Channel", "Channel")
                .WithMany("GroupMemberships")
                .HasForeignKey("ChannelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Crispy.Domain.Entities.ChannelGroup", "ChannelGroup")
                .WithMany("Memberships")
                .HasForeignKey("ChannelGroupId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Channel");
            b.Navigation("ChannelGroup");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Episode", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Series", "Series")
                .WithMany("Episodes")
                .HasForeignKey("SeriesId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Series");
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Movie", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Series", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.StreamEndpoint", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Channel", "Channel")
                .WithMany("StreamEndpoints")
                .HasForeignKey("ChannelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Channel");
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.SyncHistory", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Source", "Source")
                .WithMany()
                .HasForeignKey("SourceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Source");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.WatchHistory", b =>
        {
            b.HasOne("Crispy.Domain.Entities.Profile", "Profile")
                .WithMany()
                .HasForeignKey("ProfileId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Profile");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Channel", b =>
        {
            b.Navigation("GroupMemberships");
            b.Navigation("StreamEndpoints");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.ChannelGroup", b =>
        {
            b.Navigation("Memberships");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.DeduplicationGroup", b =>
        {
            b.Navigation("Channels");
        });

        modelBuilder.Entity("Crispy.Domain.Entities.Series", b =>
        {
            b.Navigation("Episodes");
        });
#pragma warning restore 612, 618
    }
}
