#!/usr/bin/env bash
# Generator: outputs Rust enum definitions and replacement instructions for
# String-typed discriminator fields in models/mod.rs.
#
# This script DOES NOT modify any file — it prints generated code to stdout.
# Review the output, then apply with the printed instructions.
#
# Usage: ./scripts/rust/fix_string_enums.sh [--rust-src path]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RUST_SRC="${1:-$REPO_ROOT/rust/crates/crispy-core/src}"
MODELS_FILE="$RUST_SRC/models/mod.rs"

echo "#!/usr/bin/env bash"
echo "# AUTO-GENERATED by fix_string_enums.sh — review before applying."
echo "# Apply with: bash <(./scripts/rust/fix_string_enums.sh)"
echo ""
echo "# ── Step 1: Create value_objects/ module ───────────────────────────────────"
echo "mkdir -p \"$RUST_SRC/value_objects\""
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Helper: emit a Rust file
# ─────────────────────────────────────────────────────────────────────────────
emit_file() {
    local path="$1"
    local content="$2"
    # Use printf/tee to write — emitted as shell commands the user can pipe
    echo "cat > \"${path}\" << 'RUST_EOF'"
    echo "$content"
    echo "RUST_EOF"
    echo ""
}

# ─────────────────────────────────────────────────────────────────────────────
# 1. SourceType enum (from: Source.source_type: String)
#    Observed values in codebase: "m3u", "xtream", "stalker", "plex", "emby",
#    "jellyfin" — derived from parsers and sources.rs usage.
# ─────────────────────────────────────────────────────────────────────────────
echo "# ── Step 2: Write enum source files ────────────────────────────────────────"

emit_file "$RUST_SRC/value_objects/source_type.rs" \
'//! SourceType — discriminates IPTV/media source protocols.
use serde::{Deserialize, Serialize};

/// Discriminates the protocol/format of an IPTV or media source.
///
/// Replaces `source_type: String` in [`crate::models::Source`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum SourceType {
    /// M3U/M3U+ playlist file or URL.
    #[default]
    M3u,
    /// Xtream Codes API (username/password auth).
    Xtream,
    /// Stalker portal (MAC address auth).
    Stalker,
    /// Plex Media Server.
    Plex,
    /// Emby Media Server.
    Emby,
    /// Jellyfin Media Server.
    Jellyfin,
}

impl SourceType {
    /// Returns the canonical lowercase string used in storage and FFI.
    pub fn as_str(&self) -> &'"'"'static str {
        match self {
            Self::M3u => "m3u",
            Self::Xtream => "xtream",
            Self::Stalker => "stalker",
            Self::Plex => "plex",
            Self::Emby => "emby",
            Self::Jellyfin => "jellyfin",
        }
    }

    /// Whether this source type uses username/password credentials.
    pub fn uses_credentials(&self) -> bool {
        matches!(self, Self::Xtream | Self::Stalker)
    }

    /// Whether this source type uses a token-based auth.
    pub fn uses_token(&self) -> bool {
        matches!(self, Self::Plex | Self::Emby | Self::Jellyfin)
    }
}

impl std::fmt::Display for SourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'"'"'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for SourceType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s.to_lowercase().as_str() {
            "m3u" | "m3u+" | "m3uplus" => Ok(Self::M3u),
            "xtream" | "xtream_codes" => Ok(Self::Xtream),
            "stalker" => Ok(Self::Stalker),
            "plex" => Ok(Self::Plex),
            "emby" => Ok(Self::Emby),
            "jellyfin" => Ok(Self::Jellyfin),
            other => Err(format!("unknown source type: {other}")),
        }
    }
}

impl TryFrom<String> for SourceType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}'

# ─────────────────────────────────────────────────────────────────────────────
# 2. VodItemType enum (from: VodItem.item_type: String)
#    Observed values: "movie", "series"
# ─────────────────────────────────────────────────────────────────────────────
emit_file "$RUST_SRC/value_objects/vod_item_type.rs" \
'//! VodItemType — discriminates VOD item kind.
use serde::{Deserialize, Serialize};

/// Discriminates whether a [`crate::models::VodItem`] is a movie or series.
///
/// Replaces `item_type: String` in [`crate::models::VodItem`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum VodItemType {
    /// A standalone movie.
    #[default]
    Movie,
    /// A multi-episode series.
    Series,
}

impl VodItemType {
    pub fn as_str(&self) -> &'"'"'static str {
        match self {
            Self::Movie => "movie",
            Self::Series => "series",
        }
    }

    pub fn is_movie(&self) -> bool {
        matches!(self, Self::Movie)
    }

    pub fn is_series(&self) -> bool {
        matches!(self, Self::Series)
    }
}

impl std::fmt::Display for VodItemType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'"'"'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for VodItemType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s.to_lowercase().as_str() {
            "movie" => Ok(Self::Movie),
            "series" => Ok(Self::Series),
            other => Err(format!("unknown vod item type: {other}")),
        }
    }
}

impl TryFrom<String> for VodItemType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}'

# ─────────────────────────────────────────────────────────────────────────────
# 3. CategoryType enum (from: Category.category_type and FavoriteCategory.category_type)
#    Observed values: derived from context — "live", "vod", "series", "radio"
# ─────────────────────────────────────────────────────────────────────────────
emit_file "$RUST_SRC/value_objects/category_type.rs" \
'//! CategoryType — discriminates the media category domain.
use serde::{Deserialize, Serialize};

/// Discriminates the domain of a [`crate::models::Category`].
///
/// Replaces `category_type: String` in [`crate::models::Category`]
/// and [`crate::models::FavoriteCategory`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum CategoryType {
    /// Live TV channels.
    #[default]
    Live,
    /// Video on demand (movies).
    Vod,
    /// Series/TV shows.
    Series,
    /// Radio streams.
    Radio,
}

impl CategoryType {
    pub fn as_str(&self) -> &'"'"'static str {
        match self {
            Self::Live => "live",
            Self::Vod => "vod",
            Self::Series => "series",
            Self::Radio => "radio",
        }
    }
}

impl std::fmt::Display for CategoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'"'"'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for CategoryType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s.to_lowercase().as_str() {
            "live" | "channel" | "channels" => Ok(Self::Live),
            "vod" | "movie" | "movies" => Ok(Self::Vod),
            "series" => Ok(Self::Series),
            "radio" => Ok(Self::Radio),
            other => Err(format!("unknown category type: {other}")),
        }
    }
}

impl TryFrom<String> for CategoryType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}'

# ─────────────────────────────────────────────────────────────────────────────
# 4. EpgMatchMethod enum (from: EpgMapping.match_method: String)
# ─────────────────────────────────────────────────────────────────────────────
emit_file "$RUST_SRC/value_objects/epg_match_method.rs" \
'//! EpgMatchMethod — how an EPG mapping was established.
use serde::{Deserialize, Serialize};

/// Records the mechanism used to match a channel to an EPG source.
///
/// Replaces `match_method: String` in [`crate::models::EpgMapping`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum EpgMatchMethod {
    /// Matched automatically by tvg-id.
    #[default]
    TvgId,
    /// Matched automatically by channel name similarity.
    NameFuzzy,
    /// Matched manually by the user.
    Manual,
    /// Matched by tvg-name field.
    TvgName,
}

impl EpgMatchMethod {
    pub fn as_str(&self) -> &'"'"'static str {
        match self {
            Self::TvgId => "tvg_id",
            Self::NameFuzzy => "name_fuzzy",
            Self::Manual => "manual",
            Self::TvgName => "tvg_name",
        }
    }
}

impl std::fmt::Display for EpgMatchMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'"'"'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for EpgMatchMethod {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "tvg_id" | "tvgid" => Ok(Self::TvgId),
            "name_fuzzy" | "fuzzy" => Ok(Self::NameFuzzy),
            "manual" => Ok(Self::Manual),
            "tvg_name" | "tvgname" => Ok(Self::TvgName),
            other => Err(format!("unknown match method: {other}")),
        }
    }
}

impl TryFrom<String> for EpgMatchMethod {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}'

# ─────────────────────────────────────────────────────────────────────────────
# 5. SyncPhase enum (from: SyncProgress.phase: String)
# ─────────────────────────────────────────────────────────────────────────────
emit_file "$RUST_SRC/value_objects/sync_phase.rs" \
'//! SyncPhase — tracks which stage of a sync operation is active.
use serde::{Deserialize, Serialize};

/// Tracks the current phase of a source sync operation.
///
/// Replaces `phase: String` in [`crate::models::SyncProgress`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum SyncPhase {
    #[default]
    Idle,
    Connecting,
    Authenticating,
    FetchingChannels,
    FetchingVod,
    FetchingSeries,
    FetchingEpg,
    Persisting,
    Done,
    Failed,
}

impl SyncPhase {
    pub fn as_str(&self) -> &'"'"'static str {
        match self {
            Self::Idle => "idle",
            Self::Connecting => "connecting",
            Self::Authenticating => "authenticating",
            Self::FetchingChannels => "fetching_channels",
            Self::FetchingVod => "fetching_vod",
            Self::FetchingSeries => "fetching_series",
            Self::FetchingEpg => "fetching_epg",
            Self::Persisting => "persisting",
            Self::Done => "done",
            Self::Failed => "failed",
        }
    }

    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Done | Self::Failed | Self::Idle)
    }
}

impl std::fmt::Display for SyncPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'"'"'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for SyncPhase {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "idle" => Ok(Self::Idle),
            "connecting" => Ok(Self::Connecting),
            "authenticating" => Ok(Self::Authenticating),
            "fetching_channels" => Ok(Self::FetchingChannels),
            "fetching_vod" => Ok(Self::FetchingVod),
            "fetching_series" => Ok(Self::FetchingSeries),
            "fetching_epg" => Ok(Self::FetchingEpg),
            "persisting" => Ok(Self::Persisting),
            "done" => Ok(Self::Done),
            "failed" => Ok(Self::Failed),
            other => Err(format!("unknown sync phase: {other}")),
        }
    }
}

impl TryFrom<String> for SyncPhase {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}'

# ─────────────────────────────────────────────────────────────────────────────
# 6. mod.rs for value_objects/
# ─────────────────────────────────────────────────────────────────────────────
emit_file "$RUST_SRC/value_objects/mod.rs" \
'//! Domain value objects — typed replacements for primitive String fields.
pub mod category_type;
pub mod epg_match_method;
pub mod source_type;
pub mod sync_phase;
pub mod vod_item_type;

pub use category_type::CategoryType;
pub use epg_match_method::EpgMatchMethod;
pub use source_type::SourceType;
pub use sync_phase::SyncPhase;
pub use vod_item_type::VodItemType;'

# ─────────────────────────────────────────────────────────────────────────────
# Step 3: Emit field replacement instructions (sed commands)
# These are SAFE previews — user must review before running.
# ─────────────────────────────────────────────────────────────────────────────
echo "# ── Step 3: Replace String fields in models/mod.rs ────────────────────────"
echo "# Review each sed command carefully before running."
echo ""
echo "# Add value_objects module to lib.rs (run once):"
echo "# grep -q 'mod value_objects' \"$RUST_SRC/lib.rs\" || \\"
echo "#   sed -i '/^pub mod models;/a pub mod value_objects;' \"$RUST_SRC/lib.rs\""
echo ""
echo "# Add value_objects use to models/mod.rs (run once):"
echo "# Add at top of file after existing use statements:"
echo "# use crate::value_objects::{CategoryType, EpgMatchMethod, SourceType, SyncPhase, VodItemType};"
echo ""
echo "# Field replacements:"
echo "# Source.source_type: String -> SourceType"
echo "# sed -i 's/pub source_type: String/pub source_type: SourceType/' \"$MODELS_FILE\""
echo ""
echo "# VodItem.item_type: String -> VodItemType"
echo "# sed -i 's/pub item_type: String/pub item_type: VodItemType/' \"$MODELS_FILE\""
echo ""
echo "# Category.category_type / FavoriteCategory.category_type: String -> CategoryType"
echo "# sed -i 's/pub category_type: String/pub category_type: CategoryType/' \"$MODELS_FILE\""
echo ""
echo "# EpgMapping.match_method: String -> EpgMatchMethod"
echo "# sed -i 's/pub match_method: String/pub match_method: EpgMatchMethod/' \"$MODELS_FILE\""
echo ""
echo "# SyncProgress.phase: String -> SyncPhase"
echo "# sed -i 's/pub phase: String/pub phase: SyncPhase/' \"$MODELS_FILE\""
echo ""
echo "# ── Step 4: Fix call sites ──────────────────────────────────────────────────"
echo "# After applying field changes, cargo check will reveal all call sites."
echo "# Pattern for service files using .source_type == \"xtream\":"
echo "#   OLD: source.source_type == \"xtream\""
echo "#   NEW: source.source_type == SourceType::Xtream"
echo "#        source.source_type.as_str() == \"xtream\"  // for SQL binding"
echo ""
echo "# Pattern for rusqlite row reads:"
echo "#   OLD: row.get::<_, String>(idx)?"
echo "#   NEW: let raw: String = row.get::<_, String>(idx)?;"
echo "#        let val = SourceType::try_from(raw).unwrap_or_default();"
echo ""
echo "# ── Step 5: Verify ──────────────────────────────────────────────────────────"
echo "# cd \"$REPO_ROOT/rust\" && cargo check -p crispy-core 2>&1 | head -50"
echo "# cd \"$REPO_ROOT/rust\" && cargo test -p crispy-core 2>&1 | tail -20"
