//! J-01: Cold First Launch — Cinematic Welcome to First Content
//!
//! Dream: "Cinematic mandatory onboarding. Brand animation, profile creation,
//! dynamic per-type source form, progressive content loading.
//! Content visible within 90 seconds."
//!
//! This journey captures the actual rendered state at each onboarding step.
//! Screenshots document what IS rendered — the review pipeline catches
//! deviations from the spec.

use crate::harness::{db::TestDb, journey_runner::Journey, renderer::ScreenshotHarness};
use crate::{AppState, AppWindow, OnboardingState};
use slint::ComponentHandle;

// AppWindow and OnboardingState are generated by slint::include_modules!() in
// screenshots.rs (the test binary root). They are in scope here because this
// module is compiled as part of the screenshots test binary.

pub struct J01;

impl Journey for J01 {
    const ID: &'static str = "j01";
    const NAME: &'static str = "Cold First Launch — Cinematic Welcome to First Content";
    const DEPENDS_ON: &'static [&'static str] = &[];

    fn run(harness: &ScreenshotHarness, _db: &TestDb) {
        // ── Step 0: Welcome screen ─────────────────────────────────────────

        // Activate onboarding (simulates first-launch detection)
        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_is_active(true);
            ui.global::<OnboardingState>().set_step(0);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "welcome_screen",
            "App launches",
            "Cinematic welcome screen visible",
        );

        // ── Step 1: Profile creation ───────────────────────────────────────

        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_step(1);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "profile_creation",
            "Profile name input",
            "Profile creation form shown",
        );

        // Type a profile name character by character
        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_profile_name("Alex".into());
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "profile_name_entered",
            "User types name",
            "Profile name entered",
        );

        // ── Step 2: Add source ─────────────────────────────────────────────

        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_step(2);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "source_type_selector",
            "Source type selection",
            "Source type picker shown",
        );

        // Show M3U source form (default type is "m3u")
        if let Some(ui) = harness.ui::<AppWindow>() {
            // Set the editing source type to m3u
            let mut src = ui.global::<AppState>().get_editing_source();
            src.source_type = "m3u".into();
            ui.global::<AppState>().set_editing_source(src);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "source_form_m3u",
            "M3U form",
            "Dynamic M3U form with URL field",
        );

        // Switch to Xtream type
        if let Some(ui) = harness.ui::<AppWindow>() {
            let mut src = ui.global::<AppState>().get_editing_source();
            src.source_type = "xtream".into();
            ui.global::<AppState>().set_editing_source(src);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "source_form_xtream",
            "Xtream form",
            "Dynamic Xtream form with server/user/pass",
        );

        // Switch to Stalker type
        if let Some(ui) = harness.ui::<AppWindow>() {
            let mut src = ui.global::<AppState>().get_editing_source();
            src.source_type = "stalker".into();
            ui.global::<AppState>().set_editing_source(src);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "source_form_stalker",
            "Stalker form",
            "Dynamic Stalker form with portal/MAC",
        );

        // Fill in M3U source for actual validation flow
        if let Some(ui) = harness.ui::<AppWindow>() {
            let mut src = ui.global::<AppState>().get_editing_source();
            src.source_type = "m3u".into();
            src.name = "Test Source".into();
            src.url = "http://example.com/playlist.m3u".into();
            ui.global::<AppState>().set_editing_source(src);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "source_validating",
            "Validate source",
            "Validation in progress",
        );

        // ── Step 3: Preferences ────────────────────────────────────────────

        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_step(3);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "preferences",
            "Preferences step",
            "Language and preferences selection",
        );

        // ── Step 4: Complete ───────────────────────────────────────────────

        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_step(4);
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "onboarding_complete",
            "Content loaded",
            "Content visible, onboarding done",
        );

        // Deactivate onboarding — app transitions to main content
        if let Some(ui) = harness.ui::<AppWindow>() {
            ui.global::<OnboardingState>().set_is_active(false);
            ui.global::<AppState>().set_active_screen(0); // Home
            slint::platform::update_timers_and_animations();
        }

        harness.assert_screenshot(
            "home_screen_post_onboarding",
            "Home screen",
            "Home screen visible after onboarding completes",
        );
    }
}
