// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Normalize a channel name for fuzzy matching.
String normalizeChannelName({required String name}) =>
    RustLib.instance.api.crateApiAlgorithmsNormalizeChannelName(name: name);

/// Normalize a stream URL for comparison.
String normalizeStreamUrl({required String url}) =>
    RustLib.instance.api.crateApiAlgorithmsNormalizeStreamUrl(url: url);

/// Try to base64-decode a string. Returns decoded
/// string or the original if not valid base64.
String tryBase64Decode({required String input}) =>
    RustLib.instance.api.crateApiAlgorithmsTryBase64Decode(input: input);

/// Validate a MAC address format.
bool validateMacAddress({required String mac}) =>
    RustLib.instance.api.crateApiAlgorithmsValidateMacAddress(mac: mac);

/// Strip colons from a MAC address.
String macToDeviceId({required String mac}) =>
    RustLib.instance.api.crateApiAlgorithmsMacToDeviceId(mac: mac);

/// Guess search domains for channel logo lookup.
List<String> guessLogoDomains({required String name}) =>
    RustLib.instance.api.crateApiAlgorithmsGuessLogoDomains(name: name);

/// Normalize an API base URL to scheme://host[:port].
String normalizeApiBaseUrl({required String url}) =>
    RustLib.instance.api.crateApiAlgorithmsNormalizeApiBaseUrl(url: url);

/// Detect duplicate channels by normalized stream URL.
/// Input: JSON array of Channel objects.
/// Returns JSON array of DuplicateGroup objects.
Future<String> detectDuplicateChannels({required String json}) =>
    RustLib.instance.api.crateApiAlgorithmsDetectDuplicateChannels(json: json);

/// Check if a channel ID is a duplicate.
bool isDuplicate({required String groupsJson, required String channelId}) =>
    RustLib.instance.api.crateApiAlgorithmsIsDuplicate(
      groupsJson: groupsJson,
      channelId: channelId,
    );

/// Get all duplicate IDs across all groups.
Future<List<String>> getAllDuplicateIds({required String groupsJson}) => RustLib
    .instance
    .api
    .crateApiAlgorithmsGetAllDuplicateIds(groupsJson: groupsJson);

/// Filter and sort a JSON-encoded channel list.
///
/// `channels_json` — JSON array of Channel objects.
/// `params_json`   — JSON-encoded FilterSortParams.
/// Returns JSON array of Channel after filtering and
/// sorting.
Future<String> filterAndSortChannels({
  required String channelsJson,
  required String paramsJson,
}) => RustLib.instance.api.crateApiAlgorithmsFilterAndSortChannels(
  channelsJson: channelsJson,
  paramsJson: paramsJson,
);

/// Sort a JSON-encoded list of favourite channels.
///
/// `channels_json` — JSON array of Channel objects.
/// `sort_mode`     — One of `"recentlyAdded"`,
///   `"nameAsc"`, `"nameDesc"`, `"contentType"`.
String sortFavorites({
  required String channelsJson,
  required String sortMode,
}) => RustLib.instance.api.crateApiAlgorithmsSortFavorites(
  channelsJson: channelsJson,
  sortMode: sortMode,
);

/// Sort categories with favourites first.
///
/// `categories_json` — JSON array of category name strings.
/// `favorites_json`  — JSON array of favourite category
///   name strings.
/// Returns JSON array of sorted String.
String sortCategoriesWithFavorites({
  required String categoriesJson,
  required String favoritesJson,
}) => RustLib.instance.api.crateApiAlgorithmsSortCategoriesWithFavorites(
  categoriesJson: categoriesJson,
  favoritesJson: favoritesJson,
);

/// Extract unique categories from VOD items filtered by
/// type.
///
/// `items_json` — JSON array of VodItem.
/// `vod_type`   — Type to filter by (e.g. `"movie"`,
///   `"series"`).
/// Returns JSON array of sorted String.
Future<String> buildTypeCategories({
  required String itemsJson,
  required String vodType,
}) => RustLib.instance.api.crateApiAlgorithmsBuildTypeCategories(
  itemsJson: itemsJson,
  vodType: vodType,
);

/// Build a category ID-to-name map from raw JSON.
/// Returns JSON object {id: name}.
Future<String> buildCategoryMap({required String categoriesJson}) => RustLib
    .instance
    .api
    .crateApiAlgorithmsBuildCategoryMap(categoriesJson: categoriesJson);

/// Search channels, VOD, and EPG.
/// Returns JSON of SearchResults.
Future<String> searchContent({
  required String query,
  required String channelsJson,
  required String vodItemsJson,
  required String epgEntriesJson,
  required String filterJson,
}) => RustLib.instance.api.crateApiAlgorithmsSearchContent(
  query: query,
  channelsJson: channelsJson,
  vodItemsJson: vodItemsJson,
  epgEntriesJson: epgEntriesJson,
  filterJson: filterJson,
);

/// Enrich search results with channel/VOD metadata.
/// Returns JSON array of EnrichedSearchResult.
Future<String> enrichSearchResults({
  required String resultsJson,
  required String channelsJson,
  required String vodItemsJson,
}) => RustLib.instance.api.crateApiAlgorithmsEnrichSearchResults(
  resultsJson: resultsJson,
  channelsJson: channelsJson,
  vodItemsJson: vodItemsJson,
);

/// Compute recommendation sections from VOD items,
/// channels, and watch history.
/// Returns JSON array of RecommendationSection.
Future<String> computeRecommendations({
  required String vodItemsJson,
  required String channelsJson,
  required String historyJson,
  required List<String> favoriteChannelIds,
  required List<String> favoriteVodIds,
  required int maxAllowedRating,
  required PlatformInt64 nowUtcMs,
}) => RustLib.instance.api.crateApiAlgorithmsComputeRecommendations(
  vodItemsJson: vodItemsJson,
  channelsJson: channelsJson,
  historyJson: historyJson,
  favoriteChannelIds: favoriteChannelIds,
  favoriteVodIds: favoriteVodIds,
  maxAllowedRating: maxAllowedRating,
  nowUtcMs: nowUtcMs,
);

/// Parse recommendation sections into typed structs.
/// Returns JSON array of TypedRecommendationSection.
Future<String> parseRecommendationSections({required String sectionsJson}) =>
    RustLib.instance.api.crateApiAlgorithmsParseRecommendationSections(
      sectionsJson: sectionsJson,
    );

/// Deserialize recommendation sections into
/// fully-merged structs with typed enums and all
/// supplementary fields (poster, category, etc.).
/// Returns JSON array of FullRecommendationSection.
Future<String> deserializeRecommendationSections({
  required String sectionsJson,
}) => RustLib.instance.api.crateApiAlgorithmsDeserializeRecommendationSections(
  sectionsJson: sectionsJson,
);

/// Merge local and cloud backup JSON objects.
/// Returns the merged JSON string.
Future<String> mergeCloudBackups({
  required String localJson,
  required String cloudJson,
  required String currentDeviceId,
}) => RustLib.instance.api.crateApiAlgorithmsMergeCloudBackups(
  localJson: localJson,
  cloudJson: cloudJson,
  currentDeviceId: currentDeviceId,
);

/// Hash a PIN using SHA-256.
/// Returns 64-char hex hash.
String hashPin({required String pin}) =>
    RustLib.instance.api.crateApiAlgorithmsHashPin(pin: pin);

/// Verify a PIN against a stored hash.
bool verifyPin({required String inputPin, required String storedHash}) =>
    RustLib.instance.api.crateApiAlgorithmsVerifyPin(
      inputPin: inputPin,
      storedHash: storedHash,
    );

/// Check if a value looks like a SHA-256 hash.
bool isHashedPin({required String value}) =>
    RustLib.instance.api.crateApiAlgorithmsIsHashedPin(value: value);

/// Completion threshold (0.95): items at or above
/// this progress ratio are considered finished.
double completionThreshold() =>
    RustLib.instance.api.crateApiAlgorithmsCompletionThreshold();

/// Next-episode threshold (0.90): items at or above
/// this progress ratio trigger next-episode suggestions.
double nextEpisodeThreshold() =>
    RustLib.instance.api.crateApiAlgorithmsNextEpisodeThreshold();

/// Sign an S3 request using AWS Signature V4.
/// Returns JSON map of headers to add.
Future<String> signS3Request({
  required String method,
  required String path,
  required PlatformInt64 nowUtcMs,
  required String host,
  required String region,
  required String accessKey,
  required String secretKey,
  String? extraHeadersJson,
}) => RustLib.instance.api.crateApiAlgorithmsSignS3Request(
  method: method,
  path: path,
  nowUtcMs: nowUtcMs,
  host: host,
  region: region,
  accessKey: accessKey,
  secretKey: secretKey,
  extraHeadersJson: extraHeadersJson,
);

/// Generate a pre-signed URL for an S3 GET request.
/// Returns the full URL string.
Future<String> generatePresignedUrl({
  required String endpoint,
  required String bucket,
  required String objectKey,
  required String region,
  required String accessKey,
  required String secretKey,
  required PlatformInt64 expirySecs,
  required PlatformInt64 nowUtcMs,
}) => RustLib.instance.api.crateApiAlgorithmsGeneratePresignedUrl(
  endpoint: endpoint,
  bucket: bucket,
  objectKey: objectKey,
  region: region,
  accessKey: accessKey,
  secretKey: secretKey,
  expirySecs: expirySecs,
  nowUtcMs: nowUtcMs,
);

/// Format a timestamp as "HH:MM" in a timezone.
String formatEpgTime({
  required PlatformInt64 timestampMs,
  required double offsetHours,
}) => RustLib.instance.api.crateApiAlgorithmsFormatEpgTime(
  timestampMs: timestampMs,
  offsetHours: offsetHours,
);

/// Format a timestamp as "Day DD Mon HH:MM".
String formatEpgDatetime({
  required PlatformInt64 timestampMs,
  required double offsetHours,
}) => RustLib.instance.api.crateApiAlgorithmsFormatEpgDatetime(
  timestampMs: timestampMs,
  offsetHours: offsetHours,
);

/// Format duration in minutes as "Xh Ym".
String formatDurationMinutes({required int minutes}) => RustLib.instance.api
    .crateApiAlgorithmsFormatDurationMinutes(minutes: minutes);

/// Calculate duration between timestamps in minutes.
int durationBetweenMs({
  required PlatformInt64 startMs,
  required PlatformInt64 endMs,
}) => RustLib.instance.api.crateApiAlgorithmsDurationBetweenMs(
  startMs: startMs,
  endMs: endMs,
);

/// Format a playback position as "HH:MM:SS" or "MM:SS".
///
/// Hours are shown when the total media length (`duration_ms`) is >= 1 hour.
/// The position values are derived from `position_ms`, clamped to zero if
/// negative. All fields are zero-padded to 2 digits.
String formatPlaybackDuration({
  required PlatformInt64 positionMs,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiAlgorithmsFormatPlaybackDuration(
  positionMs: positionMs,
  durationMs: durationMs,
);

/// Returns the UTC offset in minutes for the given IANA timezone name
/// at the given epoch millisecond. DST-aware via chrono-tz.
///
/// Returns 0 for "system", "UTC", or unknown timezone names.
int getTimezoneOffsetMinutes({
  required String tzName,
  required PlatformInt64 epochMs,
}) => RustLib.instance.api.crateApiAlgorithmsGetTimezoneOffsetMinutes(
  tzName: tzName,
  epochMs: epochMs,
);

/// Applies the DST-aware timezone offset to a UTC epoch_ms.
/// Returns adjusted epoch_ms for display purposes.
/// Returns epoch_ms unchanged for "system", "UTC", or unknown timezones.
PlatformInt64 applyTimezoneOffset({
  required PlatformInt64 epochMs,
  required String tzName,
}) => RustLib.instance.api.crateApiAlgorithmsApplyTimezoneOffset(
  epochMs: epochMs,
  tzName: tzName,
);

/// Formats epoch_ms as "HH:MM:SS" in the given IANA timezone. DST-aware.
/// Falls back to UTC for "system", "UTC", or unknown timezones.
String formatTimeWithSeconds({
  required PlatformInt64 epochMs,
  required String tzName,
}) => RustLib.instance.api.crateApiAlgorithmsFormatTimeWithSeconds(
  epochMs: epochMs,
  tzName: tzName,
);

/// Calculate progress ratio from position and duration.
/// Returns clamped 0.0-1.0.
double calculateWatchProgress({
  required PlatformInt64 positionMs,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiAlgorithmsCalculateWatchProgress(
  positionMs: positionMs,
  durationMs: durationMs,
);

/// Filter watch positions for continue watching.
/// Returns JSON array of WatchPositionEntry.
Future<String> filterContinueWatchingPositions({
  required String json,
  required BigInt limit,
}) => RustLib.instance.api.crateApiAlgorithmsFilterContinueWatchingPositions(
  json: json,
  limit: limit,
);

/// Filter VOD items to those added within the last
/// `cutoff_days` days, sorted newest-first.
///
/// `items_json`   — JSON array of VodItem.
/// `cutoff_days`  — number of days to look back.
/// `now_ms`       — current Unix time in milliseconds.
/// Returns JSON array of VodItem.
Future<String> filterRecentlyAdded({
  required String itemsJson,
  required int cutoffDays,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsFilterRecentlyAdded(
  itemsJson: itemsJson,
  cutoffDays: cutoffDays,
  nowMs: nowMs,
);

/// Computes the current watch streak in consecutive
/// calendar days.
///
/// `timestamps_json` — JSON array of epoch-ms i64 values.
/// `now_ms`          — current time as epoch-ms.
/// Returns streak count as u32.
int computeWatchStreak({
  required String timestampsJson,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsComputeWatchStreak(
  timestampsJson: timestampsJson,
  nowMs: nowMs,
);

/// Computes aggregated viewing statistics for a profile.
///
/// `history_json` — JSON array of watch-history objects.
/// `now_ms`       — current time as epoch-ms.
/// Returns JSON-serialised ProfileStats.
Future<String> computeProfileStats({
  required String historyJson,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsComputeProfileStats(
  historyJson: historyJson,
  nowMs: nowMs,
);

/// Merges two WatchHistory JSON arrays, deduplicates by
/// `id` (first occurrence wins), and sorts by
/// `last_watched` descending.
///
/// Returns a JSON array.
Future<String> mergeDedupSortHistory({
  required String aJson,
  required String bJson,
}) => RustLib.instance.api.crateApiAlgorithmsMergeDedupSortHistory(
  aJson: aJson,
  bJson: bJson,
);

/// Filters a WatchHistory JSON array by
/// continue-watching status.
///
/// `history_json` — JSON array of WatchHistory.
/// `filter`       — `"all"`, `"watching"`, or
///   `"completed"`.
/// Returns a JSON array.
Future<String> filterByCwStatus({
  required String historyJson,
  required String filter,
}) => RustLib.instance.api.crateApiAlgorithmsFilterByCwStatus(
  historyJson: historyJson,
  filter: filter,
);

/// Returns a JSON array of series IDs whose `updated_at`
/// is within the last `days` days relative to `now_ms`.
///
/// `series_json` — JSON array of objects with `id` and
///   optional `updated_at` epoch-ms.
/// `days`        — look-back window in days.
/// `now_ms`      — current time as epoch-ms.
Future<String> seriesIdsWithNewEpisodes({
  required String seriesJson,
  required int days,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsSeriesIdsWithNewEpisodes(
  seriesJson: seriesJson,
  days: days,
  nowMs: nowMs,
);

/// Counts in-progress episodes for a given `series_id`.
///
/// `history_json` — JSON array of watch-history-like
///   objects with series_id, media_type, duration_ms,
///   position_ms.
/// `series_id`    — the series to count for.
/// Returns count as usize.
BigInt countInProgressEpisodes({
  required String historyJson,
  required String seriesId,
}) => RustLib.instance.api.crateApiAlgorithmsCountInProgressEpisodes(
  historyJson: historyJson,
  seriesId: seriesId,
);

/// Match a group name to a Material icon identifier.
String matchGroupIcon({required String groupName}) =>
    RustLib.instance.api.crateApiAlgorithmsMatchGroupIcon(groupName: groupName);

/// Group enriched search results by media type.
/// Returns JSON of GroupedResults.
Future<String> groupSearchResults({
  required String resultsJson,
  required String channelsJson,
  required String vodJson,
  required String epgJson,
}) => RustLib.instance.api.crateApiAlgorithmsGroupSearchResults(
  resultsJson: resultsJson,
  channelsJson: channelsJson,
  vodJson: vodJson,
  epgJson: epgJson,
);

/// Search channels by matching live program title.
Future<String> searchChannelsByLiveProgram({
  required String epgMapJson,
  required String query,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsSearchChannelsByLiveProgram(
  epgMapJson: epgMapJson,
  query: query,
  nowMs: nowMs,
);

/// Merge EPG-matched channel IDs into a base list.
Future<String> mergeEpgMatchedChannels({
  required String baseJson,
  required String allChannelsJson,
  required String matchedIdsJson,
  required String epgOverridesJson,
}) => RustLib.instance.api.crateApiAlgorithmsMergeEpgMatchedChannels(
  baseJson: baseJson,
  allChannelsJson: allChannelsJson,
  matchedIdsJson: matchedIdsJson,
  epgOverridesJson: epgOverridesJson,
);

/// Build merged/deduped search categories.
String buildSearchCategories({
  required String vodCategoriesJson,
  required String channelGroupsJson,
}) => RustLib.instance.api.crateApiAlgorithmsBuildSearchCategories(
  vodCategoriesJson: vodCategoriesJson,
  channelGroupsJson: channelGroupsJson,
);

/// Check if a PIN lockout is currently active.
bool isLockActive({
  required PlatformInt64 lockedUntilMs,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsIsLockActive(
  lockedUntilMs: lockedUntilMs,
  nowMs: nowMs,
);

/// Return ms remaining in a PIN lockout.
PlatformInt64 lockRemainingMs({
  required PlatformInt64 lockedUntilMs,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsLockRemainingMs(
  lockedUntilMs: lockedUntilMs,
  nowMs: nowMs,
);

/// Resolve next episodes for continue-watching.
Future<String> resolveNextEpisodes({
  required String entriesJson,
  required String vodItemsJson,
  required double threshold,
}) => RustLib.instance.api.crateApiAlgorithmsResolveNextEpisodes(
  entriesJson: entriesJson,
  vodItemsJson: vodItemsJson,
  threshold: threshold,
);

/// Count episodes per season.
String episodeCountBySeason({required String episodesJson}) => RustLib
    .instance
    .api
    .crateApiAlgorithmsEpisodeCountBySeason(episodesJson: episodesJson);

/// Determine badge kind for a VOD item.
String vodBadgeKind({
  int? year,
  PlatformInt64? addedAtMs,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiAlgorithmsVodBadgeKind(
  year: year,
  addedAtMs: addedAtMs,
  nowMs: nowMs,
);

/// Derive a stable, platform-independent watch-history ID from a stream URL.
///
/// Returns the first 16 hex characters of the SHA-256 hash of the URL.
/// This replaces Dart's unstable `hashCode.toRadixString(36)` which varies
/// across platforms, isolates, and SDK versions.
String deriveWatchHistoryId({required String url}) =>
    RustLib.instance.api.crateApiAlgorithmsDeriveWatchHistoryId(url: url);

/// Find similar VOD items by genre/category overlap.
Future<String> similarVodItems({
  required String itemsJson,
  required String itemId,
  required BigInt limit,
}) => RustLib.instance.api.crateApiAlgorithmsSimilarVodItems(
  itemsJson: itemsJson,
  itemId: itemId,
  limit: limit,
);
