// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load all channels as JSON array.
Future<String> loadChannels() =>
    RustLib.instance.api.crateApiChannelsLoadChannels();

/// Save channels from JSON array. Returns count.
Future<BigInt> saveChannels({required String json}) =>
    RustLib.instance.api.crateApiChannelsSaveChannels(json: json);

/// Load channels filtered by source IDs. Returns JSON array.
///
/// Deserialises `source_ids_json` as `Vec<String>`. An empty
/// array returns ALL channels (same as `load_channels`).
Future<String> getChannelsBySources({required String sourceIdsJson}) => RustLib
    .instance
    .api
    .crateApiChannelsGetChannelsBySources(sourceIdsJson: sourceIdsJson);

/// Load channels by IDs. Returns JSON array.
Future<String> getChannelsByIds({required List<String> ids}) =>
    RustLib.instance.api.crateApiChannelsGetChannelsByIds(ids: ids);

/// Delete channels not in keep_ids for a source.
/// Returns count deleted.
Future<BigInt> deleteRemovedChannels({
  required String sourceId,
  required List<String> keepIds,
}) => RustLib.instance.api.crateApiChannelsDeleteRemovedChannels(
  sourceId: sourceId,
  keepIds: keepIds,
);

/// Get favourite channel IDs for a profile.
Future<List<String>> getFavorites({required String profileId}) =>
    RustLib.instance.api.crateApiChannelsGetFavorites(profileId: profileId);

/// Add a channel to profile favourites.
Future<void> addFavorite({
  required String profileId,
  required String channelId,
}) => RustLib.instance.api.crateApiChannelsAddFavorite(
  profileId: profileId,
  channelId: channelId,
);

/// Remove a channel from profile favourites.
Future<void> removeFavorite({
  required String profileId,
  required String channelId,
}) => RustLib.instance.api.crateApiChannelsRemoveFavorite(
  profileId: profileId,
  channelId: channelId,
);

/// Load categories filtered by source IDs as JSON object {type: [names]}.
///
/// Deserialises `source_ids_json` as `Vec<String>`. An empty
/// array returns ALL categories (same as `load_categories`).
Future<String> getCategoriesBySources({required String sourceIdsJson}) =>
    RustLib.instance.api.crateApiChannelsGetCategoriesBySources(
      sourceIdsJson: sourceIdsJson,
    );

/// Load categories as JSON object {type: [names]}.
Future<String> loadCategories() =>
    RustLib.instance.api.crateApiChannelsLoadCategories();

/// Save categories from JSON object {source_id: str, categories: {type: [names]}}.
Future<void> saveCategories({required String sourceId, required String json}) =>
    RustLib.instance.api.crateApiChannelsSaveCategories(
      sourceId: sourceId,
      json: json,
    );

/// Get favourite category names for profile + type.
Future<List<String>> getFavoriteCategories({
  required String profileId,
  required String categoryType,
}) => RustLib.instance.api.crateApiChannelsGetFavoriteCategories(
  profileId: profileId,
  categoryType: categoryType,
);

/// Add a category to profile favourites.
Future<void> addFavoriteCategory({
  required String profileId,
  required String categoryType,
  required String categoryName,
}) => RustLib.instance.api.crateApiChannelsAddFavoriteCategory(
  profileId: profileId,
  categoryType: categoryType,
  categoryName: categoryName,
);

/// Remove a category from profile favourites.
Future<void> removeFavoriteCategory({
  required String profileId,
  required String categoryType,
  required String categoryName,
}) => RustLib.instance.api.crateApiChannelsRemoveFavoriteCategory(
  profileId: profileId,
  categoryType: categoryType,
  categoryName: categoryName,
);

/// Save custom channel order for profile + group.
Future<void> saveChannelOrder({
  required String profileId,
  required String groupName,
  required List<String> channelIds,
}) => RustLib.instance.api.crateApiChannelsSaveChannelOrder(
  profileId: profileId,
  groupName: groupName,
  channelIds: channelIds,
);

/// Load channel order as JSON {channel_id: index}
/// or null if no custom order.
Future<String?> loadChannelOrder({
  required String profileId,
  required String groupName,
}) => RustLib.instance.api.crateApiChannelsLoadChannelOrder(
  profileId: profileId,
  groupName: groupName,
);

/// Reset channel order for profile + group.
Future<void> resetChannelOrder({
  required String profileId,
  required String groupName,
}) => RustLib.instance.api.crateApiChannelsResetChannelOrder(
  profileId: profileId,
  groupName: groupName,
);

/// Sort channels by number then name (in-place).
/// Input/output: JSON array of Channel.
Future<String> sortChannelsJson({required String json}) =>
    RustLib.instance.api.crateApiChannelsSortChannelsJson(json: json);

/// Resolve category IDs to names in channels.
/// Returns JSON array of Channel.
Future<String> resolveChannelCategories({
  required String channelsJson,
  required String catMapJson,
}) => RustLib.instance.api.crateApiChannelsResolveChannelCategories(
  channelsJson: channelsJson,
  catMapJson: catMapJson,
);

/// Extract unique sorted group names from channels.
Future<List<String>> extractSortedGroups({required String channelsJson}) =>
    RustLib.instance.api.crateApiChannelsExtractSortedGroups(
      channelsJson: channelsJson,
    );

/// Find the duplicate group containing a channel.
/// Returns JSON of DuplicateGroup or null.
Future<String?> findGroupForChannel({
  required String groupsJson,
  required String channelId,
}) => RustLib.instance.api.crateApiChannelsFindGroupForChannel(
  groupsJson: groupsJson,
  channelId: channelId,
);

/// Filter channels by source access.
/// Returns JSON array of channels.
///
/// Note: returns `String` (not `Result`) because the underlying algorithm
/// returns a fallback empty array `[]` on parse errors rather than
/// propagating them. Changing to `Result` would require FRB codegen.
Future<String> filterChannelsBySource({
  required String channelsJson,
  required String accessibleSourceIdsJson,
  required bool isAdmin,
}) => RustLib.instance.api.crateApiChannelsFilterChannelsBySource(
  channelsJson: channelsJson,
  accessibleSourceIdsJson: accessibleSourceIdsJson,
  isAdmin: isAdmin,
);
