// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load all recordings as JSON array.
Future<String> loadRecordings() =>
    RustLib.instance.api.crateApiDvrLoadRecordings();

/// Save a recording from JSON.
Future<void> saveRecording({required String json}) =>
    RustLib.instance.api.crateApiDvrSaveRecording(json: json);

/// Update an existing recording from JSON.
Future<void> updateRecording({required String json}) =>
    RustLib.instance.api.crateApiDvrUpdateRecording(json: json);

/// Delete a recording by ID.
Future<void> deleteRecording({required String id}) =>
    RustLib.instance.api.crateApiDvrDeleteRecording(id: id);

/// Fetch commercial markers for a given recording by ID.
Future<String> getRecordingMarkers({required String recordingId}) => RustLib
    .instance
    .api
    .crateApiDvrGetRecordingMarkers(recordingId: recordingId);

/// Load all storage backends as JSON array.
Future<String> loadStorageBackends() =>
    RustLib.instance.api.crateApiDvrLoadStorageBackends();

/// Save a storage backend from JSON.
Future<void> saveStorageBackend({required String json}) =>
    RustLib.instance.api.crateApiDvrSaveStorageBackend(json: json);

/// Delete a storage backend by ID.
Future<void> deleteStorageBackend({required String id}) =>
    RustLib.instance.api.crateApiDvrDeleteStorageBackend(id: id);

/// Load all transfer tasks as JSON array.
Future<String> loadTransferTasks() =>
    RustLib.instance.api.crateApiDvrLoadTransferTasks();

/// Save a transfer task from JSON.
Future<void> saveTransferTask({required String json}) =>
    RustLib.instance.api.crateApiDvrSaveTransferTask(json: json);

/// Update a transfer task from JSON.
Future<void> updateTransferTask({required String json}) =>
    RustLib.instance.api.crateApiDvrUpdateTransferTask(json: json);

/// Delete a transfer task by ID.
Future<void> deleteTransferTask({required String id}) =>
    RustLib.instance.api.crateApiDvrDeleteTransferTask(id: id);

/// Load watch history as JSON array.
Future<String> loadWatchHistory() =>
    RustLib.instance.api.crateApiDvrLoadWatchHistory();

/// Save a watch history entry from JSON.
Future<void> saveWatchHistory({required String json}) =>
    RustLib.instance.api.crateApiDvrSaveWatchHistory(json: json);

/// Delete a watch history entry by ID.
Future<void> deleteWatchHistory({required String id}) =>
    RustLib.instance.api.crateApiDvrDeleteWatchHistory(id: id);

/// Delete all watch history entries. Returns count.
Future<BigInt> clearAllWatchHistory() =>
    RustLib.instance.api.crateApiDvrClearAllWatchHistory();

/// Load all reminders as JSON array.
Future<String> loadReminders() =>
    RustLib.instance.api.crateApiDvrLoadReminders();

/// Save a reminder from JSON.
Future<void> saveReminder({required String json}) =>
    RustLib.instance.api.crateApiDvrSaveReminder(json: json);

/// Delete a reminder by ID.
Future<void> deleteReminder({required String id}) =>
    RustLib.instance.api.crateApiDvrDeleteReminder(id: id);

/// Delete all fired reminders.
Future<void> clearFiredReminders() =>
    RustLib.instance.api.crateApiDvrClearFiredReminders();

/// Mark a reminder as fired by ID.
Future<void> markReminderFired({required String id}) =>
    RustLib.instance.api.crateApiDvrMarkReminderFired(id: id);

/// Expand recurring recordings into concrete instances.
/// Returns JSON array of RecordingInstance.
Future<String> expandRecurringRecordings({
  required String recordingsJson,
  required PlatformInt64 nowUtcMs,
}) => RustLib.instance.api.crateApiDvrExpandRecurringRecordings(
  recordingsJson: recordingsJson,
  nowUtcMs: nowUtcMs,
);

/// Check if a candidate recording conflicts with
/// existing recordings on the same channel.
Future<bool> detectRecordingConflict({
  required String recordingsJson,
  String? excludeId,
  required String channelName,
  required PlatformInt64 startUtcMs,
  required PlatformInt64 endUtcMs,
}) => RustLib.instance.api.crateApiDvrDetectRecordingConflict(
  recordingsJson: recordingsJson,
  excludeId: excludeId,
  channelName: channelName,
  startUtcMs: startUtcMs,
  endUtcMs: endUtcMs,
);

/// Sanitize a string for use as a filename.
String sanitizeFilename({required String name}) =>
    RustLib.instance.api.crateApiDvrSanitizeFilename(name: name);

/// Filter watch history for "continue watching".
/// Returns JSON array of WatchHistory items.
Future<String> filterContinueWatching({
  required String historyJson,
  String? mediaType,
  String? profileId,
}) => RustLib.instance.api.crateApiDvrFilterContinueWatching(
  historyJson: historyJson,
  mediaType: mediaType,
  profileId: profileId,
);

/// Filter watch history for cross-device items.
/// Returns JSON array of WatchHistory items.
Future<String> filterCrossDevice({
  required String historyJson,
  required String currentDeviceId,
  required PlatformInt64 cutoffUtcMs,
}) => RustLib.instance.api.crateApiDvrFilterCrossDevice(
  historyJson: historyJson,
  currentDeviceId: currentDeviceId,
  cutoffUtcMs: cutoffUtcMs,
);

/// Whether the given role can view a recording.
bool canViewRecording({
  required String role,
  required String recordingOwnerId,
  required String currentProfileId,
}) => RustLib.instance.api.crateApiDvrCanViewRecording(
  role: role,
  recordingOwnerId: recordingOwnerId,
  currentProfileId: currentProfileId,
);

/// Whether the given role can delete a recording.
bool canDeleteRecording({
  required String role,
  required String recordingOwnerId,
  required String currentProfileId,
}) => RustLib.instance.api.crateApiDvrCanDeleteRecording(
  role: role,
  recordingOwnerId: recordingOwnerId,
  currentProfileId: currentProfileId,
);

/// Returns IDs of recordings that should start now.
///
/// Input: JSON array of recording objects with at
/// least: `{ "id", "status", "startTime", "endTime" }`.
///
/// Returns: JSON array of recording ID strings.
Future<String> getRecordingsToStart({
  required String recordingsJson,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiDvrGetRecordingsToStart(
  recordingsJson: recordingsJson,
  nowMs: nowMs,
);

/// Compute storage breakdown for recordings.
Future<String> computeStorageBreakdown({
  required String recordingsJson,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiDvrComputeStorageBreakdown(
  recordingsJson: recordingsJson,
  nowMs: nowMs,
);

/// Filter recordings by search query.
Future<String> filterDvrRecordings({
  required String recordingsJson,
  required String query,
}) => RustLib.instance.api.crateApiDvrFilterDvrRecordings(
  recordingsJson: recordingsJson,
  query: query,
);

/// Classify a file by its extension.
String classifyFileType({required String filename}) =>
    RustLib.instance.api.crateApiDvrClassifyFileType(filename: filename);

/// Sort remote files by the given order.
Future<String> sortRemoteFiles({
  required String filesJson,
  required String order,
}) => RustLib.instance.api.crateApiDvrSortRemoteFiles(
  filesJson: filesJson,
  order: order,
);
