// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load EPG entries as JSON {channel_id: [entries]}.
Future<String> loadEpgEntries() =>
    RustLib.instance.api.crateApiEpgLoadEpgEntries();

/// Load EPG entries for specific channels within a time window.
Future<String> getEpgsForChannels({
  required List<String> channelIds,
  required PlatformInt64 startTime,
  required PlatformInt64 endTime,
}) => RustLib.instance.api.crateApiEpgGetEpgsForChannels(
  channelIds: channelIds,
  startTime: startTime,
  endTime: endTime,
);

/// Load EPG entries filtered by source IDs. Returns JSON {channel_id: [entries]}.
///
/// Deserialises `source_ids_json` as `Vec<String>`. An empty
/// array returns ALL EPG entries (same as `load_epg_entries`).
Future<String> getEpgBySources({required String sourceIdsJson}) => RustLib
    .instance
    .api
    .crateApiEpgGetEpgBySources(sourceIdsJson: sourceIdsJson);

/// Save EPG entries from JSON {channel_id: [entries]}.
Future<BigInt> saveEpgEntries({required String json}) =>
    RustLib.instance.api.crateApiEpgSaveEpgEntries(json: json);

/// Delete EPG entries older than N days.
Future<BigInt> evictStaleEpg({required PlatformInt64 days}) =>
    RustLib.instance.api.crateApiEpgEvictStaleEpg(days: days);

/// Download, parse, match, and save XMLTV EPG asynchronously.
Future<BigInt> syncXmltvEpg({required String url}) =>
    RustLib.instance.api.crateApiEpgSyncXmltvEpg(url: url);

/// Download, parse, match, and save Xtream short EPG batches asynchronously.
Future<BigInt> syncXtreamEpg({
  required String baseUrl,
  required String username,
  required String password,
  required String channelsJson,
}) => RustLib.instance.api.crateApiEpgSyncXtreamEpg(
  baseUrl: baseUrl,
  username: username,
  password: password,
  channelsJson: channelsJson,
);

/// Download, parse, match, and save Stalker short EPG batches asynchronously.
Future<BigInt> syncStalkerEpg({
  required String baseUrl,
  required String channelsJson,
}) => RustLib.instance.api.crateApiEpgSyncStalkerEpg(
  baseUrl: baseUrl,
  channelsJson: channelsJson,
);

/// Delete all EPG entries.
Future<void> clearEpgEntries() =>
    RustLib.instance.api.crateApiEpgClearEpgEntries();

/// Match EPG entries to channels using 6 strategies.
/// Returns JSON `{"entries":{...},"stats":{...}}`
Future<String> matchEpgToChannels({
  required String entriesJson,
  required String channelsJson,
  required String displayNamesJson,
}) => RustLib.instance.api.crateApiEpgMatchEpgToChannels(
  entriesJson: entriesJson,
  channelsJson: channelsJson,
  displayNamesJson: displayNamesJson,
);

/// Build a catch-up URL for a channel + EPG entry.
/// Input: channel JSON, start/end Unix timestamps.
/// Returns the archive URL or null.
Future<String?> buildCatchupUrl({
  required String channelJson,
  required PlatformInt64 startUtc,
  required PlatformInt64 endUtc,
}) => RustLib.instance.api.crateApiEpgBuildCatchupUrl(
  channelJson: channelJson,
  startUtc: startUtc,
  endUtc: endUtc,
);

/// Parse Xtream short EPG listings.
/// Returns JSON array of EpgEntry objects.
Future<String> parseXtreamShortEpg({
  required String listingsJson,
  required String channelId,
}) => RustLib.instance.api.crateApiEpgParseXtreamShortEpg(
  listingsJson: listingsJson,
  channelId: channelId,
);

/// Merges new EPG entries into existing entries,
/// deduplicating by `startTime`.
///
/// Both inputs are JSON objects:
/// `{ "channelId": [ { "startTime": epochMs, ... } ] }`
///
/// Returns merged JSON object.
Future<String> mergeEpgWindow({
  required String existingJson,
  required String newJson,
}) => RustLib.instance.api.crateApiEpgMergeEpgWindow(
  existingJson: existingJson,
  newJson: newJson,
);

/// Filter EPG entries for upcoming programs on
/// favorite channels.
Future<String> filterUpcomingPrograms({
  required String epgMapJson,
  required String favoritesJson,
  required PlatformInt64 nowMs,
  required int windowMinutes,
  required BigInt limit,
}) => RustLib.instance.api.crateApiEpgFilterUpcomingPrograms(
  epgMapJson: epgMapJson,
  favoritesJson: favoritesJson,
  nowMs: nowMs,
  windowMinutes: windowMinutes,
  limit: limit,
);
