// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Rust backend with a database path.
/// Must be called once before any other API function.
Future<void> initBackend({required String dbPath}) =>
    RustLib.instance.api.crateApiLifecycleInitBackend(dbPath: dbPath);

/// Subscribe to data-change events from the Rust
/// backend. Returns a `Stream<String>` of
/// JSON-encoded `DataChangeEvent` objects on the
/// Dart side. Call once at app startup.
Stream<String> subscribeDataEvents() =>
    RustLib.instance.api.crateApiLifecycleSubscribeDataEvents();

/// Returns the crispy-core version string.
String crispyVersion() => RustLib.instance.api.crateApiLifecycleCrispyVersion();
