// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Parse M3U/M3U8 playlist content.
/// Returns JSON `{"channels":[...],"epg_url":...}`
Future<String> parseM3U({required String content}) =>
    RustLib.instance.api.crateApiParsersParseM3U(content: content);

/// Parse XMLTV EPG content.
/// Returns JSON array of EPG entries.
Future<String> parseEpg({required String content}) =>
    RustLib.instance.api.crateApiParsersParseEpg(content: content);

/// Extract XMLTV channel display names.
/// Returns JSON `{"xmltv_id":"display_name",...}`
Future<String> extractEpgChannelNames({required String content}) => RustLib
    .instance
    .api
    .crateApiParsersExtractEpgChannelNames(content: content);

/// Parse Xtream `get_vod_streams` JSON response.
/// Returns JSON array of VodItem.
Future<String> parseVodStreams({
  required String json,
  required String baseUrl,
  required String username,
  required String password,
  String? sourceId,
}) => RustLib.instance.api.crateApiParsersParseVodStreams(
  json: json,
  baseUrl: baseUrl,
  username: username,
  password: password,
  sourceId: sourceId,
);

/// Parse Xtream `get_series` JSON response.
/// Returns JSON array of VodItem.
Future<String> parseSeries({required String json, String? sourceId}) => RustLib
    .instance
    .api
    .crateApiParsersParseSeries(json: json, sourceId: sourceId);

/// Parse episodes from `get_series_info` response.
/// Returns JSON array of VodItem.
Future<String> parseEpisodes({
  required String json,
  required String baseUrl,
  required String username,
  required String password,
  required String seriesId,
}) => RustLib.instance.api.crateApiParsersParseEpisodes(
  json: json,
  baseUrl: baseUrl,
  username: username,
  password: password,
  seriesId: seriesId,
);

/// Parse VOD entries from M3U channel maps.
/// Returns JSON array of VodItem.
Future<String> parseM3UVod({required String json, String? sourceId}) => RustLib
    .instance
    .api
    .crateApiParsersParseM3UVod(json: json, sourceId: sourceId);

/// Parse WebVTT thumbnail sprite sheet.
/// Returns JSON of ThumbnailSprite or null.
Future<String?> parseVttThumbnails({
  required String content,
  required String baseUrl,
}) => RustLib.instance.api.crateApiParsersParseVttThumbnails(
  content: content,
  baseUrl: baseUrl,
);

/// Parse a BIF file's index table.
/// Returns JSON array of `{timestamp_ms, offset, length}`.
Future<String> parseBifIndex({required List<int> data}) =>
    RustLib.instance.api.crateApiParsersParseBifIndex(data: data);

/// Find the BIF thumbnail nearest to the target timestamp
/// and extract its JPEG bytes.
///
/// `index_json` is the JSON array returned by `parse_bif_index`.
/// Returns the JPEG bytes, or an empty vec if not found.
Future<Uint8List> getBifThumbnail({
  required List<int> data,
  required String indexJson,
  required PlatformInt64 timestampMs,
}) => RustLib.instance.api.crateApiParsersGetBifThumbnail(
  data: data,
  indexJson: indexJson,
  timestampMs: timestampMs,
);

/// Parse Stalker EPG entries for a channel.
/// Returns JSON array of EpgEntry objects.
Future<String> parseStalkerEpg({
  required String json,
  required String channelId,
}) => RustLib.instance.api.crateApiParsersParseStalkerEpg(
  json: json,
  channelId: channelId,
);

/// Parse Stalker VOD items list.
/// Returns JSON array of VodItem objects.
Future<String> parseStalkerVodItems({
  required String json,
  required String baseUrl,
  String? vodType,
  String? sourceId,
}) => RustLib.instance.api.crateApiParsersParseStalkerVodItems(
  json: json,
  baseUrl: baseUrl,
  vodType: vodType,
  sourceId: sourceId,
);

/// Parse Stalker channels paginated result.
/// Returns JSON of StalkerPaginatedResult.
Future<String> parseStalkerChannels({required String json}) =>
    RustLib.instance.api.crateApiParsersParseStalkerChannels(json: json);

/// Parse Stalker live streams into Channel objects.
/// Returns JSON array of Channel.
Future<String> parseStalkerLiveStreams({
  required String json,
  required String sourceId,
  required String baseUrl,
}) => RustLib.instance.api.crateApiParsersParseStalkerLiveStreams(
  json: json,
  sourceId: sourceId,
  baseUrl: baseUrl,
);

/// Build a stream URL from a Stalker `cmd` field.
/// Returns the resolved URL string.
String buildStalkerStreamUrl({required String cmd, required String baseUrl}) =>
    RustLib.instance.api.crateApiParsersBuildStalkerStreamUrl(
      cmd: cmd,
      baseUrl: baseUrl,
    );

/// Parse a Stalker `create_link` response.
/// Returns the authenticated stream URL or null.
Future<String?> parseStalkerCreateLink({
  required String json,
  required String baseUrl,
}) => RustLib.instance.api.crateApiParsersParseStalkerCreateLink(
  json: json,
  baseUrl: baseUrl,
);

/// Parse Stalker categories from genres response.
/// Returns JSON array of StalkerCategory.
Future<String> parseStalkerCategories({required String json}) =>
    RustLib.instance.api.crateApiParsersParseStalkerCategories(json: json);

/// Parse Stalker VOD paginated result.
/// Returns JSON of StalkerPaginatedResult.
Future<String> parseStalkerVodResult({required String json}) =>
    RustLib.instance.api.crateApiParsersParseStalkerVodResult(json: json);

/// Build an Xtream API action URL.
String buildXtreamActionUrl({
  required String baseUrl,
  required String username,
  required String password,
  required String action,
  String? paramsJson,
}) => RustLib.instance.api.crateApiParsersBuildXtreamActionUrl(
  baseUrl: baseUrl,
  username: username,
  password: password,
  action: action,
  paramsJson: paramsJson,
);

/// Build an Xtream stream URL.
String buildXtreamStreamUrl({
  required String baseUrl,
  required String username,
  required String password,
  required PlatformInt64 streamId,
  required String streamType,
  required String extension_,
}) => RustLib.instance.api.crateApiParsersBuildXtreamStreamUrl(
  baseUrl: baseUrl,
  username: username,
  password: password,
  streamId: streamId,
  streamType: streamType,
  extension_: extension_,
);

/// Build an Xtream catchup/timeshift URL.
String buildXtreamCatchupUrl({
  required String baseUrl,
  required String username,
  required String password,
  required PlatformInt64 streamId,
  required PlatformInt64 startUtc,
  required int durationMinutes,
}) => RustLib.instance.api.crateApiParsersBuildXtreamCatchupUrl(
  baseUrl: baseUrl,
  username: username,
  password: password,
  streamId: streamId,
  startUtc: startUtc,
  durationMinutes: durationMinutes,
);

/// Parse Xtream live streams JSON into channels.
/// Returns JSON array of Channel.
Future<String> parseXtreamLiveStreams({
  required String json,
  required String baseUrl,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiParsersParseXtreamLiveStreams(
  json: json,
  baseUrl: baseUrl,
  username: username,
  password: password,
);

/// Parse Xtream categories into sorted names.
/// Returns JSON array of strings.
Future<String> parseXtreamCategories({required String json}) =>
    RustLib.instance.api.crateApiParsersParseXtreamCategories(json: json);

/// Parse S3 ListBucketResult XML response.
/// Returns JSON array of S3Object.
Future<String> parseS3ListObjects({required String xml}) =>
    RustLib.instance.api.crateApiParsersParseS3ListObjects(xml: xml);
