// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get a setting value by key.
Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiSettingsGetSetting(key: key);

/// Set a setting value.
Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSettingsSetSetting(key: key, value: value);

/// Remove a setting.
Future<void> removeSetting({required String key}) =>
    RustLib.instance.api.crateApiSettingsRemoveSetting(key: key);

/// Get last sync time for a source (Unix seconds).
Future<PlatformInt64?> getLastSyncTime({required String sourceId}) =>
    RustLib.instance.api.crateApiSettingsGetLastSyncTime(sourceId: sourceId);

/// Set last sync time for a source (Unix seconds).
Future<void> setLastSyncTime({
  required String sourceId,
  required PlatformInt64 timestamp,
}) => RustLib.instance.api.crateApiSettingsSetLastSyncTime(
  sourceId: sourceId,
  timestamp: timestamp,
);

/// Delete all data from all tables.
Future<void> clearAll() => RustLib.instance.api.crateApiSettingsClearAll();

/// Export all data as a JSON backup string.
Future<String> exportBackup() =>
    RustLib.instance.api.crateApiSettingsExportBackup();

/// Import data from a JSON backup string.
/// Returns JSON summary of imported entities.
Future<String> importBackup({required String json}) =>
    RustLib.instance.api.crateApiSettingsImportBackup(json: json);

/// Deep-merge two JSON objects.
String deepMergeJson({
  required String baseJson,
  required String overridesJson,
}) => RustLib.instance.api.crateApiSettingsDeepMergeJson(
  baseJson: baseJson,
  overridesJson: overridesJson,
);

/// Set a value at a dot-separated path in a JSON
/// object.
String setNestedValue({
  required String mapJson,
  required String dotPath,
  required String valueJson,
}) => RustLib.instance.api.crateApiSettingsSetNestedValue(
  mapJson: mapJson,
  dotPath: dotPath,
  valueJson: valueJson,
);

/// Detect GPU info for video upscaling. Returns JSON.
/// Does NOT require backend init — can be called
/// anytime.
Future<String> detectGpu() => RustLib.instance.api.crateApiSettingsDetectGpu();

/// Determines cloud sync direction from timestamps and
/// device IDs.
///
/// Returns one of: `"upload"`, `"download"`,
/// `"no_change"`, `"conflict"`.
///
/// Pure CPU — no DB access required.
String determineSyncDirection({
  required PlatformInt64 localMs,
  required PlatformInt64 cloudMs,
  required PlatformInt64 lastSyncMs,
  required String localDevice,
  required String cloudDevice,
}) => RustLib.instance.api.crateApiSettingsDetermineSyncDirection(
  localMs: localMs,
  cloudMs: cloudMs,
  lastSyncMs: lastSyncMs,
  localDevice: localDevice,
  cloudDevice: cloudDevice,
);

/// Load all saved layouts as JSON array.
Future<String> loadSavedLayouts() =>
    RustLib.instance.api.crateApiSettingsLoadSavedLayouts();

/// Save a layout from JSON.
Future<void> saveSavedLayout({required String json}) =>
    RustLib.instance.api.crateApiSettingsSaveSavedLayout(json: json);

/// Delete a saved layout by ID.
Future<void> deleteSavedLayout({required String id}) =>
    RustLib.instance.api.crateApiSettingsDeleteSavedLayout(id: id);

/// Get a saved layout by ID (direct query).
Future<String> getSavedLayoutById({required String id}) =>
    RustLib.instance.api.crateApiSettingsGetSavedLayoutById(id: id);

/// Load all search history as JSON array.
Future<String> loadSearchHistory() =>
    RustLib.instance.api.crateApiSettingsLoadSearchHistory();

/// Save a search entry from JSON.
Future<void> saveSearchEntry({required String json}) =>
    RustLib.instance.api.crateApiSettingsSaveSearchEntry(json: json);

/// Delete a search entry by ID.
Future<void> deleteSearchEntry({required String id}) =>
    RustLib.instance.api.crateApiSettingsDeleteSearchEntry(id: id);

/// Clear all search history.
Future<void> clearSearchHistory() =>
    RustLib.instance.api.crateApiSettingsClearSearchHistory();

/// Delete search history by query text
/// (case-insensitive). Returns count deleted.
Future<BigInt> deleteSearchByQuery({required String query}) =>
    RustLib.instance.api.crateApiSettingsDeleteSearchByQuery(query: query);

/// Resolve a single channel name to a tv-logos URL.
Future<String?> resolveChannelLogo({required String name}) =>
    RustLib.instance.api.crateApiSettingsResolveChannelLogo(name: name);

/// Resolve logos for a batch of channel names.
/// Returns JSON map of `name → url`.
Future<String> resolveLogosBatch({required String namesJson}) => RustLib
    .instance
    .api
    .crateApiSettingsResolveLogosBatch(namesJson: namesJson);

/// Check if the logo index needs refreshing (>24 h old).
Future<bool> isLogoIndexStale() =>
    RustLib.instance.api.crateApiSettingsIsLogoIndexStale();

/// Fetch the logo index from the GitHub API and save it.
Future<void> refreshLogoIndex() =>
    RustLib.instance.api.crateApiSettingsRefreshLogoIndex();

/// Decode a BlurHash string into BMP image bytes.
///
/// Returns minimal 32-bit BMP data suitable for `Image.memory()`.
/// Default size: 16×16 (~1 KB). Use as placeholder while full
/// image loads.
Uint8List decodeBlurhash({
  required String hash,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSettingsDecodeBlurhash(
  hash: hash,
  width: width,
  height: height,
);
