// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new smart channel group. Returns its UUID.
Future<String> createSmartGroup({required String name}) =>
    RustLib.instance.api.crateApiSmartGroupsCreateSmartGroup(name: name);

/// Delete a smart group and all its members.
Future<void> deleteSmartGroup({required String groupId}) =>
    RustLib.instance.api.crateApiSmartGroupsDeleteSmartGroup(groupId: groupId);

/// Rename a smart group.
Future<void> renameSmartGroup({
  required String groupId,
  required String name,
}) => RustLib.instance.api.crateApiSmartGroupsRenameSmartGroup(
  groupId: groupId,
  name: name,
);

/// Add a channel to a smart group with a given priority.
Future<void> addSmartGroupMember({
  required String groupId,
  required String channelId,
  required String sourceId,
  required int priority,
}) => RustLib.instance.api.crateApiSmartGroupsAddSmartGroupMember(
  groupId: groupId,
  channelId: channelId,
  sourceId: sourceId,
  priority: priority,
);

/// Remove a channel from a smart group.
Future<void> removeSmartGroupMember({
  required String groupId,
  required String channelId,
}) => RustLib.instance.api.crateApiSmartGroupsRemoveSmartGroupMember(
  groupId: groupId,
  channelId: channelId,
);

/// Reorder members of a smart group.
Future<void> reorderSmartGroupMembers({
  required String groupId,
  required String orderedChannelIdsJson,
}) => RustLib.instance.api.crateApiSmartGroupsReorderSmartGroupMembers(
  groupId: groupId,
  orderedChannelIdsJson: orderedChannelIdsJson,
);

/// Load all smart groups with their members as JSON.
Future<String> getSmartGroupsJson() =>
    RustLib.instance.api.crateApiSmartGroupsGetSmartGroupsJson();

/// Get the smart group a channel belongs to, if any.
Future<String?> getSmartGroupForChannel({required String channelId}) => RustLib
    .instance
    .api
    .crateApiSmartGroupsGetSmartGroupForChannel(channelId: channelId);

/// Get smart group alternatives for a channel (excluding same source).
Future<String> getSmartGroupAlternatives({required String channelId}) => RustLib
    .instance
    .api
    .crateApiSmartGroupsGetSmartGroupAlternatives(channelId: channelId);

/// Auto-detect potential smart group candidates across sources.
Future<String> detectSmartGroupCandidates() =>
    RustLib.instance.api.crateApiSmartGroupsDetectSmartGroupCandidates();
