// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get all sources as JSON array.
Future<String> getSources() => RustLib.instance.api.crateApiSourcesGetSources();

/// Get a single source by ID as JSON (null if not found).
Future<String> getSource({required String id}) =>
    RustLib.instance.api.crateApiSourcesGetSource(id: id);

/// Save a source from JSON.
Future<void> saveSource({required String json}) =>
    RustLib.instance.api.crateApiSourcesSaveSource(json: json);

/// Delete a source and cascade-delete all its data.
Future<void> deleteSource({required String id}) =>
    RustLib.instance.api.crateApiSourcesDeleteSource(id: id);

/// Reorder sources. Takes JSON array of source IDs.
Future<void> reorderSources({required String idsJson}) =>
    RustLib.instance.api.crateApiSourcesReorderSources(idsJson: idsJson);

/// Update sync status on a source.
Future<void> updateSourceSyncStatus({
  required String id,
  required String status,
  String? error,
  PlatformInt64? syncTimeMs,
}) => RustLib.instance.api.crateApiSourcesUpdateSourceSyncStatus(
  id: id,
  status: status,
  error: error,
  syncTimeMs: syncTimeMs,
);
