// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failover_map`

/// Record a stream stall event for a URL hash.
Future<void> recordStreamStall({required String urlHash}) => RustLib
    .instance
    .api
    .crateApiStreamHealthRecordStreamStall(urlHash: urlHash);

/// Record a buffer health sample for a URL hash.
Future<void> recordBufferSample({
  required String urlHash,
  required double cacheDurationSecs,
}) => RustLib.instance.api.crateApiStreamHealthRecordBufferSample(
  urlHash: urlHash,
  cacheDurationSecs: cacheDurationSecs,
);

/// Record time-to-first-frame for a URL hash.
Future<void> recordTtff({
  required String urlHash,
  required PlatformInt64 ttffMs,
}) => RustLib.instance.api.crateApiStreamHealthRecordTtff(
  urlHash: urlHash,
  ttffMs: ttffMs,
);

/// Get the health score for a URL hash (0.0–1.0).
Future<double> getStreamHealthScore({required String urlHash}) => RustLib
    .instance
    .api
    .crateApiStreamHealthGetStreamHealthScore(urlHash: urlHash);

/// Get health scores for multiple URL hashes.
///
/// Returns JSON: `{"hash1": 0.8, "hash2": 0.5}`
Future<String> getStreamHealthScores({required String urlHashesJson}) => RustLib
    .instance
    .api
    .crateApiStreamHealthGetStreamHealthScores(urlHashesJson: urlHashesJson);

/// Keep only the newest `max_entries` stream health rows.
Future<BigInt> pruneStreamHealth({required PlatformInt64 maxEntries}) => RustLib
    .instance
    .api
    .crateApiStreamHealthPruneStreamHealth(maxEntries: maxEntries);

/// Feed a failover event and get the action decision.
///
/// Returns JSON: `{"action":"none"|"start_warming"|"swap_warm"}`
Future<String> evaluateFailoverEvent({
  required String urlHash,
  required String eventType,
  required double value,
}) => RustLib.instance.api.crateApiStreamHealthEvaluateFailoverEvent(
  urlHash: urlHash,
  eventType: eventType,
  value: value,
);

/// Reset in-memory failover counters for a URL.
Future<void> resetFailoverState({required String urlHash}) => RustLib
    .instance
    .api
    .crateApiStreamHealthResetFailoverState(urlHash: urlHash);

/// Rank alternative streams for failover.
///
/// Takes a target channel JSON and all channels JSON,
/// returns ranked alternatives as JSON array.
Future<String> rankStreamAlternatives({
  required String targetJson,
  required String allChannelsJson,
  required String healthScoresJson,
}) => RustLib.instance.api.crateApiStreamHealthRankStreamAlternatives(
  targetJson: targetJson,
  allChannelsJson: allChannelsJson,
  healthScoresJson: healthScoresJson,
);

/// Extract a US broadcast call sign from a channel name.
///
/// Returns the call sign or empty string if none found.
String extractCallSign({required String name}) =>
    RustLib.instance.api.crateApiStreamHealthExtractCallSign(name: name);
