// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Subscribe to sync progress events from Rust.
/// Returns a `Stream<String>` of JSON-encoded `SyncProgress`
/// objects on the Dart side.
Stream<String> subscribeSyncProgress() =>
    RustLib.instance.api.crateApiSyncSubscribeSyncProgress();

/// Verify Xtream credentials. Returns `true` if authenticated.
Future<bool> verifyXtreamCredentials({
  required String baseUrl,
  required String username,
  required String password,
  required bool acceptInvalidCerts,
}) => RustLib.instance.api.crateApiSyncVerifyXtreamCredentials(
  baseUrl: baseUrl,
  username: username,
  password: password,
  acceptInvalidCerts: acceptInvalidCerts,
);

/// Full Xtream source sync. Returns JSON `SyncReport`.
Future<String> syncXtreamSource({
  required String baseUrl,
  required String username,
  required String password,
  required String sourceId,
  required bool acceptInvalidCerts,
}) => RustLib.instance.api.crateApiSyncSyncXtreamSource(
  baseUrl: baseUrl,
  username: username,
  password: password,
  sourceId: sourceId,
  acceptInvalidCerts: acceptInvalidCerts,
);

/// Full M3U source sync. Returns JSON `SyncReport`.
Future<String> syncM3USource({
  required String url,
  required String sourceId,
  required bool acceptInvalidCerts,
}) => RustLib.instance.api.crateApiSyncSyncM3USource(
  url: url,
  sourceId: sourceId,
  acceptInvalidCerts: acceptInvalidCerts,
);

/// Verify Stalker portal MAC authentication. Returns `true` if accepted.
Future<bool> verifyStalkerPortal({
  required String baseUrl,
  required String macAddress,
  required bool acceptInvalidCerts,
}) => RustLib.instance.api.crateApiSyncVerifyStalkerPortal(
  baseUrl: baseUrl,
  macAddress: macAddress,
  acceptInvalidCerts: acceptInvalidCerts,
);

/// Full Stalker portal sync. Returns JSON `SyncReport`.
Future<String> syncStalkerSource({
  required String baseUrl,
  required String macAddress,
  required String sourceId,
  required bool acceptInvalidCerts,
}) => RustLib.instance.api.crateApiSyncSyncStalkerSource(
  baseUrl: baseUrl,
  macAddress: macAddress,
  sourceId: sourceId,
  acceptInvalidCerts: acceptInvalidCerts,
);
