// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get all VOD items in a profile's watchlist as a JSON string.
Future<String> getWatchlistItems({required String profileId}) => RustLib
    .instance
    .api
    .crateApiWatchlistGetWatchlistItems(profileId: profileId);

/// Add a VOD item to the profile's watchlist.
Future<void> addWatchlistItem({
  required String profileId,
  required String vodItemId,
}) => RustLib.instance.api.crateApiWatchlistAddWatchlistItem(
  profileId: profileId,
  vodItemId: vodItemId,
);

/// Remove a VOD item from the profile's watchlist.
Future<void> removeWatchlistItem({
  required String profileId,
  required String vodItemId,
}) => RustLib.instance.api.crateApiWatchlistRemoveWatchlistItem(
  profileId: profileId,
  vodItemId: vodItemId,
);
