// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check for a newer app version via GitHub Releases API.
///
/// Returns JSON with `has_update`, `latest_version`, `changelog`,
/// `download_url`, `published_at`, `assets_json`, and optional `error`.
Future<String> checkForUpdate({
  required String currentVersion,
  required String repoUrl,
}) => RustLib.instance.api.crateApiAppUpdateCheckForUpdate(
  currentVersion: currentVersion,
  repoUrl: repoUrl,
);

/// Find a platform-specific download URL from release assets JSON.
///
/// `platform`: `android`, `windows`, `linux`, `macos`.
/// Returns the first matching asset URL, or `None`.
String? getPlatformAssetUrl({
  required String assetsJson,
  required String platform,
}) => RustLib.instance.api.crateApiAppUpdateGetPlatformAssetUrl(
  assetsJson: assetsJson,
  platform: platform,
);
