// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load all bookmarks for a content item as JSON.
Future<String> loadBookmarks({required String contentId}) =>
    RustLib.instance.api.crateApiBookmarksLoadBookmarks(contentId: contentId);

/// Save a bookmark from JSON.
Future<void> saveBookmark({required String json}) =>
    RustLib.instance.api.crateApiBookmarksSaveBookmark(json: json);

/// Delete a bookmark by ID.
Future<void> deleteBookmark({required String id}) =>
    RustLib.instance.api.crateApiBookmarksDeleteBookmark(id: id);

/// Clear all bookmarks for a content item.
Future<void> clearBookmarks({required String contentId}) =>
    RustLib.instance.api.crateApiBookmarksClearBookmarks(contentId: contentId);
