// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `state_map`

/// Get the persisted tier for a URL hash.
Future<String?> getBufferTier({required String urlHash}) =>
    RustLib.instance.api.crateApiBufferGetBufferTier(urlHash: urlHash);

/// Persist a tier for a URL hash.
Future<void> setBufferTier({required String urlHash, required String tier}) =>
    RustLib.instance.api.crateApiBufferSetBufferTier(
      urlHash: urlHash,
      tier: tier,
    );

/// Prune buffer tier entries, keeping only the newest
/// `max_entries`.
Future<BigInt> pruneBufferTiers({required PlatformInt64 maxEntries}) =>
    RustLib.instance.api.crateApiBufferPruneBufferTiers(maxEntries: maxEntries);

/// Feed a buffer health sample and get back the
/// (possibly updated) tier as JSON.
///
/// Returns: `{"tier":"normal","changed":false,"readahead_secs":120}`
Future<String> evaluateBufferSample({
  required String urlHash,
  required double cacheDurationSecs,
}) => RustLib.instance.api.crateApiBufferEvaluateBufferSample(
  urlHash: urlHash,
  cacheDurationSecs: cacheDurationSecs,
);

/// Reset in-memory buffer counters for a URL (on channel change).
Future<void> resetBufferState({required String urlHash}) =>
    RustLib.instance.api.crateApiBufferResetBufferState(urlHash: urlHash);

/// Android heap-adaptive buffer cap.
///
/// Returns maximum forward buffer in MB.
PlatformInt64 getBufferCapMb({required PlatformInt64 heapMaxMb}) =>
    RustLib.instance.api.crateApiBufferGetBufferCapMb(heapMaxMb: heapMaxMb);
