// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Attempt to switch the Windows display refresh rate to best match the given FPS.
/// Returns true if successful or if no change was needed. On non-Windows platforms, returns false.
Future<bool> afrSwitchMode({required double fps}) =>
    RustLib.instance.api.crateApiDisplayAfrSwitchMode(fps: fps);

/// Restore the original display mode if it was changed.
Future<bool> afrRestoreMode() =>
    RustLib.instance.api.crateApiDisplayAfrRestoreMode();
