// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load EPG entries as JSON {channel_id: [entries]}.
Future<String> loadEpgEntries() =>
    RustLib.instance.api.crateApiEpgLoadEpgEntries();

/// Load EPG entries for specific channels within a time window.
Future<String> getEpgsForChannels({
  required List<String> channelIds,
  required PlatformInt64 startTime,
  required PlatformInt64 endTime,
}) => RustLib.instance.api.crateApiEpgGetEpgsForChannels(
  channelIds: channelIds,
  startTime: startTime,
  endTime: endTime,
);

/// Resolve internal channel IDs that have real EPG coverage in the time window.
Future<String> getEpgCoverageChannelIds({
  required List<String> channelIds,
  required PlatformInt64 startTime,
  required PlatformInt64 endTime,
}) => RustLib.instance.api.crateApiEpgGetEpgCoverageChannelIds(
  channelIds: channelIds,
  startTime: startTime,
  endTime: endTime,
);

/// Load EPG entries filtered by source IDs. Returns JSON {channel_id: [entries]}.
///
/// Deserialises `source_ids_json` as `Vec<String>`. An empty
/// array returns ALL EPG entries (same as `load_epg_entries`).
Future<String> getEpgBySources({required String sourceIdsJson}) => RustLib
    .instance
    .api
    .crateApiEpgGetEpgBySources(sourceIdsJson: sourceIdsJson);

/// Save EPG entries from JSON {channel_id: [entries]}.
Future<BigInt> saveEpgEntries({required String json}) =>
    RustLib.instance.api.crateApiEpgSaveEpgEntries(json: json);

/// Delete EPG entries older than N days.
Future<BigInt> evictStaleEpg({required PlatformInt64 days}) =>
    RustLib.instance.api.crateApiEpgEvictStaleEpg(days: days);

/// Download, parse, match, and save XMLTV EPG asynchronously.
///
/// Skips if the same URL was refreshed within the 4-hour
/// cooldown window.
Future<BigInt> syncXmltvEpg({
  required String url,
  required String sourceId,
  required bool force,
}) => RustLib.instance.api.crateApiEpgSyncXmltvEpg(
  url: url,
  sourceId: sourceId,
  force: force,
);

/// Download, parse, match, and save Xtream short EPG batches asynchronously.
///
/// Cooldown is applied to the derived XMLTV URL.
Future<BigInt> syncXtreamEpg({
  required String baseUrl,
  required String username,
  required String password,
  required String sourceId,
  required String channelsJson,
  required bool force,
}) => RustLib.instance.api.crateApiEpgSyncXtreamEpg(
  baseUrl: baseUrl,
  username: username,
  password: password,
  sourceId: sourceId,
  channelsJson: channelsJson,
  force: force,
);

/// Download, parse, match, and save Stalker short EPG batches asynchronously.
///
/// Cooldown is applied to the base URL.
Future<BigInt> syncStalkerEpg({
  required String baseUrl,
  required String mac,
  required String sourceId,
  required String channelsJson,
  required bool force,
}) => RustLib.instance.api.crateApiEpgSyncStalkerEpg(
  baseUrl: baseUrl,
  mac: mac,
  sourceId: sourceId,
  channelsJson: channelsJson,
  force: force,
);

/// Delete all EPG entries.
Future<void> clearEpgEntries() =>
    RustLib.instance.api.crateApiEpgClearEpgEntries();

/// Match EPG entries to channels using 6 strategies.
/// Returns JSON `{"entries":{...},"stats":{...}}`
Future<String> matchEpgToChannels({
  required String entriesJson,
  required String channelsJson,
  required String displayNamesJson,
}) => RustLib.instance.api.crateApiEpgMatchEpgToChannels(
  entriesJson: entriesJson,
  channelsJson: channelsJson,
  displayNamesJson: displayNamesJson,
);

/// Build a catch-up URL for a channel + EPG entry.
/// Input: channel JSON, start/end Unix timestamps.
/// Returns the archive URL or null.
Future<String?> buildCatchupUrl({
  required String channelJson,
  required PlatformInt64 startUtc,
  required PlatformInt64 endUtc,
}) => RustLib.instance.api.crateApiEpgBuildCatchupUrl(
  channelJson: channelJson,
  startUtc: startUtc,
  endUtc: endUtc,
);

/// Parse Xtream short EPG listings.
/// Returns JSON array of EpgEntry objects.
Future<String> parseXtreamShortEpg({
  required String listingsJson,
  required String channelId,
}) => RustLib.instance.api.crateApiEpgParseXtreamShortEpg(
  listingsJson: listingsJson,
  channelId: channelId,
);

/// Run confidence-based EPG matching.
/// Returns JSON array of EpgMatchCandidate objects.
Future<String> matchEpgWithConfidence({
  required String entriesJson,
  required String channelsJson,
  required String displayNamesJson,
}) => RustLib.instance.api.crateApiEpgMatchEpgWithConfidence(
  entriesJson: entriesJson,
  channelsJson: channelsJson,
  displayNamesJson: displayNamesJson,
);

/// Save an EPG mapping.
Future<void> saveEpgMapping({required String json}) =>
    RustLib.instance.api.crateApiEpgSaveEpgMapping(json: json);

/// Get all EPG mappings as JSON array.
Future<String> getEpgMappings() =>
    RustLib.instance.api.crateApiEpgGetEpgMappings();

/// Lock an EPG mapping so it won't be overridden.
Future<void> lockEpgMapping({required String channelId}) =>
    RustLib.instance.api.crateApiEpgLockEpgMapping(channelId: channelId);

/// Delete an EPG mapping.
Future<void> deleteEpgMapping({required String channelId}) =>
    RustLib.instance.api.crateApiEpgDeleteEpgMapping(channelId: channelId);

/// Get pending EPG suggestions (0.40-0.69 confidence, not locked).
Future<String> getPendingEpgSuggestions() =>
    RustLib.instance.api.crateApiEpgGetPendingEpgSuggestions();

/// Mark a channel as 24/7.
Future<void> setChannel247({required String channelId, required bool is247}) =>
    RustLib.instance.api.crateApiEpgSetChannel247(
      channelId: channelId,
      is247: is247,
    );

/// Merges new EPG entries into existing entries,
/// deduplicating by `startTime`.
///
/// Both inputs are JSON objects:
/// `{ "channelId": [ { "startTime": epochMs, ... } ] }`
///
/// Returns merged JSON object.
Future<String> mergeEpgWindow({
  required String existingJson,
  required String newJson,
}) => RustLib.instance.api.crateApiEpgMergeEpgWindow(
  existingJson: existingJson,
  newJson: newJson,
);

/// Filter EPG entries for upcoming programs on
/// favorite channels.
Future<String> filterUpcomingPrograms({
  required String epgMapJson,
  required String favoritesJson,
  required PlatformInt64 nowMs,
  required int windowMinutes,
  required BigInt limit,
}) => RustLib.instance.api.crateApiEpgFilterUpcomingPrograms(
  epgMapJson: epgMapJson,
  favoritesJson: favoritesJson,
  nowMs: nowMs,
  windowMinutes: windowMinutes,
  limit: limit,
);

/// Get EPG for a single channel via the 3-layer facade.
///
/// Resolution: L1 moka hot cache → L2 SQLite → L3 per-channel API fetch.
/// Returns JSON array of EpgEntry.
Future<String> getChannelEpg({
  required String channelId,
  required BigInt count,
}) => RustLib.instance.api.crateApiEpgGetChannelEpg(
  channelId: channelId,
  count: count,
);

/// Get EPG for multiple channels within a time window via the 3-layer facade.
///
/// Returns JSON `{channel_id: [entries]}`.
Future<String> getChannelsEpg({
  required String channelIdsJson,
  required PlatformInt64 startTime,
  required PlatformInt64 endTime,
}) => RustLib.instance.api.crateApiEpgGetChannelsEpg(
  channelIdsJson: channelIdsJson,
  startTime: startTime,
  endTime: endTime,
);

/// Invalidate the L1 hot cache for a specific channel.
Future<void> invalidateEpgCache({required String channelId}) =>
    RustLib.instance.api.crateApiEpgInvalidateEpgCache(channelId: channelId);

/// Clear all EPG caches (L1 hot cache).
Future<void> clearEpgCaches() =>
    RustLib.instance.api.crateApiEpgClearEpgCaches();

/// Get the number of channels in the L1 hot cache.
Future<BigInt> epgHotCacheSize() =>
    RustLib.instance.api.crateApiEpgEpgHotCacheSize();
