// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load all profiles as JSON array.
Future<String> loadProfiles() =>
    RustLib.instance.api.crateApiProfilesLoadProfiles();

/// Save a profile from JSON object.
Future<void> saveProfile({required String json}) =>
    RustLib.instance.api.crateApiProfilesSaveProfile(json: json);

/// Delete a profile and cascade-delete children.
Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateApiProfilesDeleteProfile(id: id);

/// Get source IDs a profile can access.
Future<List<String>> getSourceAccess({required String profileId}) =>
    RustLib.instance.api.crateApiProfilesGetSourceAccess(profileId: profileId);

/// Grant a profile access to a source.
Future<void> grantSourceAccess({
  required String profileId,
  required String sourceId,
}) => RustLib.instance.api.crateApiProfilesGrantSourceAccess(
  profileId: profileId,
  sourceId: sourceId,
);

/// Revoke a profile's access to a source.
Future<void> revokeSourceAccess({
  required String profileId,
  required String sourceId,
}) => RustLib.instance.api.crateApiProfilesRevokeSourceAccess(
  profileId: profileId,
  sourceId: sourceId,
);

/// Replace all source access for a profile.
Future<void> setSourceAccess({
  required String profileId,
  required List<String> sourceIds,
}) => RustLib.instance.api.crateApiProfilesSetSourceAccess(
  profileId: profileId,
  sourceIds: sourceIds,
);

/// Get profile IDs that have access to a source.
Future<List<String>> getProfilesForSource({required String sourceId}) => RustLib
    .instance
    .api
    .crateApiProfilesGetProfilesForSource(sourceId: sourceId);
