// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load all VOD items as JSON array.
Future<String> loadVodItems() => RustLib.instance.api.crateApiVodLoadVodItems();

/// Save VOD items from JSON array. Returns count.
Future<BigInt> saveVodItems({required String json}) =>
    RustLib.instance.api.crateApiVodSaveVodItems(json: json);

/// Load VOD items filtered by source IDs. Returns JSON array.
///
/// Deserialises `source_ids_json` as `Vec<String>`. An empty
/// array returns ALL VOD items (same as `load_vod_items`).
Future<String> getVodBySources({required String sourceIdsJson}) => RustLib
    .instance
    .api
    .crateApiVodGetVodBySources(sourceIdsJson: sourceIdsJson);

/// Load a page of VOD items filtered by source IDs, type, category, and query.
Future<String> getVodPage({
  required String sourceIdsJson,
  String? vodType,
  String? category,
  String? query,
  required String sort,
  required PlatformInt64 offset,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiVodGetVodPage(
  sourceIdsJson: sourceIdsJson,
  vodType: vodType,
  category: category,
  query: query,
  sort: sort,
  offset: offset,
  limit: limit,
);

/// Count VOD items filtered by source IDs, type, category, and query.
Future<PlatformInt64> getVodCount({
  required String sourceIdsJson,
  String? vodType,
  String? category,
  String? query,
}) => RustLib.instance.api.crateApiVodGetVodCount(
  sourceIdsJson: sourceIdsJson,
  vodType: vodType,
  category: category,
  query: query,
);

/// Load VOD categories with item counts filtered by source IDs and type.
Future<String> getVodCategories({
  required String sourceIdsJson,
  String? vodType,
}) => RustLib.instance.api.crateApiVodGetVodCategories(
  sourceIdsJson: sourceIdsJson,
  vodType: vodType,
);

/// Search VOD items by query with pagination.
Future<String> searchVod({
  required String query,
  required String sourceIdsJson,
  required PlatformInt64 offset,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiVodSearchVod(
  query: query,
  sourceIdsJson: sourceIdsJson,
  offset: offset,
  limit: limit,
);

/// Load VOD items filtered by sources, type, category, query, and sorted by sorting key.
Future<String> getFilteredVod({
  required String sourceIdsJson,
  String? itemType,
  String? category,
  String? query,
  required String sortBy,
}) => RustLib.instance.api.crateApiVodGetFilteredVod(
  sourceIdsJson: sourceIdsJson,
  itemType: itemType,
  category: category,
  query: query,
  sortBy: sortBy,
);

/// Delete VOD items not in keep_ids for a source.
Future<BigInt> deleteRemovedVodItems({
  required String sourceId,
  required List<String> keepIds,
}) => RustLib.instance.api.crateApiVodDeleteRemovedVodItems(
  sourceId: sourceId,
  keepIds: keepIds,
);

/// Find VOD alternatives from other sources matching by name + year.
/// Returns JSON array of VodItem.
/// `year` = 0 means "no year filter".
Future<String> findVodAlternatives({
  required String name,
  required int year,
  required String excludeId,
  required BigInt limit,
}) => RustLib.instance.api.crateApiVodFindVodAlternatives(
  name: name,
  year: year,
  excludeId: excludeId,
  limit: limit,
);

/// Get favourite VOD item IDs for a profile.
Future<List<String>> getVodFavorites({required String profileId}) =>
    RustLib.instance.api.crateApiVodGetVodFavorites(profileId: profileId);

/// Add a VOD item to profile favourites.
Future<void> addVodFavorite({
  required String profileId,
  required String vodItemId,
}) => RustLib.instance.api.crateApiVodAddVodFavorite(
  profileId: profileId,
  vodItemId: vodItemId,
);

/// Remove a VOD item from profile favourites.
Future<void> removeVodFavorite({
  required String profileId,
  required String vodItemId,
}) => RustLib.instance.api.crateApiVodRemoveVodFavorite(
  profileId: profileId,
  vodItemId: vodItemId,
);

/// Update the is_favorite flag on a VOD item.
Future<void> updateVodFavorite({
  required String itemId,
  required bool isFavorite,
}) => RustLib.instance.api.crateApiVodUpdateVodFavorite(
  itemId: itemId,
  isFavorite: isFavorite,
);

/// Resolve category IDs to names in VOD items.
/// Returns JSON array of VodItem.
Future<String> resolveVodCategories({
  required String itemsJson,
  required String catMapJson,
}) => RustLib.instance.api.crateApiVodResolveVodCategories(
  itemsJson: itemsJson,
  catMapJson: catMapJson,
);

/// Extract unique sorted category names from VOD.
Future<List<String>> extractSortedVodCategories({required String itemsJson}) =>
    RustLib.instance.api.crateApiVodExtractSortedVodCategories(
      itemsJson: itemsJson,
    );

/// Sort VOD items by the given criterion.
/// Input/output: JSON arrays of VodItem.
Future<String> sortVodItems({
  required String itemsJson,
  required String sortBy,
}) => RustLib.instance.api.crateApiVodSortVodItems(
  itemsJson: itemsJson,
  sortBy: sortBy,
);

/// Filter (by category/query) and sort VOD items array in memory.
Future<String> filterAndSortVodItems({
  required String itemsJson,
  String? category,
  String? query,
  required String sortBy,
}) => RustLib.instance.api.crateApiVodFilterAndSortVodItems(
  itemsJson: itemsJson,
  category: category,
  query: query,
  sortBy: sortBy,
);

/// Group VOD items by category.
/// Returns JSON VodCategoryMap.
Future<String> buildVodCategoryMap({required String itemsJson}) =>
    RustLib.instance.api.crateApiVodBuildVodCategoryMap(itemsJson: itemsJson);

/// Filter and rank top VOD items by rating.
/// Returns JSON array of VodItem.
Future<String> filterTopVod({
  required String itemsJson,
  required BigInt limit,
}) => RustLib.instance.api.crateApiVodFilterTopVod(
  itemsJson: itemsJson,
  limit: limit,
);

/// Compute per-episode progress for a series.
/// Returns JSON EpisodeProgressResult.
Future<String> computeEpisodeProgress({
  required String historyJson,
  required String seriesId,
}) => RustLib.instance.api.crateApiVodComputeEpisodeProgress(
  historyJson: historyJson,
  seriesId: seriesId,
);

/// Compute episode progress from DB for a series.
/// Returns JSON with progress_map + last_watched_url.
Future<String> computeEpisodeProgressFromDb({required String seriesId}) =>
    RustLib.instance.api.crateApiVodComputeEpisodeProgressFromDb(
      seriesId: seriesId,
    );

/// Filter VOD items by content rating.
/// Returns JSON array of allowed VodItem.
Future<String> filterVodByContentRating({
  required String itemsJson,
  required int maxRatingValue,
}) => RustLib.instance.api.crateApiVodFilterVodByContentRating(
  itemsJson: itemsJson,
  maxRatingValue: maxRatingValue,
);
