//! DVR recording algorithms ported from Dart.
//!
//! Ports logic from `dvr_service.dart`: recurring
//! recording expansion, conflict detection, filename
//! sanitization, and scheduled-recording discovery.

use std::sync::LazyLock;

use chrono::{Datelike, Duration, NaiveDate, NaiveDateTime, Timelike};
use regex::Regex;
use serde::{Deserialize, Serialize};

use crate::models::Recording;

static RE_SANITIZE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"[^\w\s-]").unwrap());

/// A concrete recording instance generated by expanding
/// a recurring recording pattern.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordingInstance {
    /// Channel display name.
    pub channel_name: String,
    /// Programme name.
    pub program_name: String,
    /// Instance start time.
    pub start_time: NaiveDateTime,
    /// Instance end time.
    pub end_time: NaiveDateTime,
    /// Channel ID.
    pub channel_id: Option<String>,
    /// Channel logo URL.
    pub channel_logo_url: Option<String>,
    /// Stream URL for the recording source.
    pub stream_url: Option<String>,
    /// Profile that owns this recording.
    pub owner_profile_id: Option<String>,
    /// Whether shared with all profiles.
    pub is_shared: bool,
}

/// Expand recurring recordings into concrete instances
/// for the next 7 days.
///
/// For each recurring recording whose `recur_days`
/// bitmask includes a given day, a
/// [`RecordingInstance`] is produced with the
/// recording's time-of-day applied to that date.
///
/// Instances that have already ended (before `now`) or
/// that already exist as non-recurring recordings are
/// skipped.
pub fn expand_recurring_recordings(
    recordings: &[Recording],
    now: NaiveDateTime,
) -> Vec<RecordingInstance> {
    let today = now.date();
    let mut instances = Vec::new();

    for rec in recordings {
        if !rec.is_recurring || rec.recur_days == 0 {
            continue;
        }

        for day_offset in 0..7 {
            let target_date = today + Duration::days(day_offset);

            // Chrono: num_days_from_monday() gives
            // Mon=0..Sun=6. Bitmask: Mon=bit0..Sun=bit6.
            let day_bit = 1 << target_date.weekday().num_days_from_monday();

            if (rec.recur_days & day_bit) == 0 {
                continue;
            }

            let instance_start = combine_date_time(target_date, rec.start_time);
            let mut instance_end = combine_date_time(target_date, rec.end_time);

            // Handle overnight recordings (e.g. 23:00–01:00):
            // if end time-of-day is before start time-of-day,
            // the recording spans midnight into the next day.
            if instance_end <= instance_start {
                instance_end += Duration::days(1);
            }

            // Skip past instances.
            if instance_end < now {
                continue;
            }

            // Skip if a non-recurring recording already
            // matches this instance.
            let already_exists = recordings.iter().any(|r| {
                !r.is_recurring
                    && r.channel_name == rec.channel_name
                    && r.program_name == rec.program_name
                    && r.start_time == instance_start
            });

            if already_exists {
                continue;
            }

            instances.push(RecordingInstance {
                channel_name: rec.channel_name.clone(),
                program_name: rec.program_name.clone(),
                start_time: instance_start,
                end_time: instance_end,
                channel_id: rec.channel_id.clone(),
                channel_logo_url: rec.channel_logo_url.clone(),
                stream_url: rec.stream_url.clone(),
                owner_profile_id: rec.owner_profile_id.clone(),
                is_shared: rec.is_shared,
            });
        }
    }

    instances
}

/// Check if a candidate recording conflicts with any
/// existing recording on the same channel with
/// overlapping time.
///
/// `exclude_id` allows ignoring a specific recording
/// (e.g. the one being edited).
pub fn detect_recording_conflict(
    recordings: &[Recording],
    exclude_id: Option<&str>,
    channel_name: &str,
    start: NaiveDateTime,
    end: NaiveDateTime,
) -> bool {
    recordings.iter().any(|r| {
        let dominated = match exclude_id {
            Some(eid) => r.id == eid,
            None => false,
        };
        !dominated && r.channel_name == channel_name && r.start_time < end && r.end_time > start
    })
}

/// Sanitize a string for use as a filename by replacing
/// non-word, non-space, non-hyphen characters with `_`.
pub fn sanitize_filename(name: &str) -> String {
    RE_SANITIZE.replace_all(name, "_").into_owned()
}

/// Find IDs of scheduled recordings whose time window
/// contains `now` (i.e. they should be started).
pub fn find_recordings_to_start(recordings: &[Recording], now: NaiveDateTime) -> Vec<String> {
    recordings
        .iter()
        .filter(|r| r.status == "scheduled" && r.start_time <= now && r.end_time > now)
        .map(|r| r.id.clone())
        .collect()
}

/// Returns IDs of recordings that should start now (JSON bridge variant).
///
/// A recording should start when:
/// - `status == "scheduled"`
/// - `startTime <= now_ms`
/// - `endTime > now_ms`
///
/// Input: JSON array of recording objects with at least:
///   `{ "id": "...", "status": "...", "startTime": epochMs, "endTime": epochMs }`
///
/// Returns: JSON array of recording ID strings that should start.
pub fn get_recordings_to_start(recordings_json: &str, now_ms: i64) -> String {
    let Ok(arr) = serde_json::from_str::<serde_json::Value>(recordings_json) else {
        return "[]".to_string();
    };
    let Some(items) = arr.as_array() else {
        return "[]".to_string();
    };

    let ids: Vec<&str> = items
        .iter()
        .filter(|r| {
            let status = r.get("status").and_then(|v| v.as_str()).unwrap_or("");
            let start = r
                .get("startTime")
                .and_then(|v| v.as_i64())
                .unwrap_or(i64::MAX);
            let end = r.get("endTime").and_then(|v| v.as_i64()).unwrap_or(0);
            status == "scheduled" && start <= now_ms && end > now_ms
        })
        .filter_map(|r| r.get("id").and_then(|v| v.as_str()))
        .collect();

    serde_json::to_string(&ids).unwrap_or_else(|_| "[]".to_string())
}

/// Compute storage breakdown statistics for a list of recordings.
///
/// Input: JSON array of recording objects with fields:
///   `id`, `status`, `channel_name`, `file_size_bytes` (nullable i64),
///   `end_time` (epoch ms).
///
/// Output JSON:
/// ```json
/// {
///   "total_bytes": N,
///   "total_count": N,
///   "categories": [{"label":"Completed","count":N,"bytes":N}],
///   "channel_bytes": {"channel_name": N},
///   "channel_counts": {"channel_name": N},
///   "cleanup_candidate_ids": ["id1", ...]
/// }
/// ```
///
/// Cleanup candidates: completed recordings older than 30 days +
/// all failed recordings, capped at 10.
pub fn compute_storage_breakdown(recordings_json: &str, now_ms: i64) -> String {
    use std::collections::HashMap;

    const EMPTY: &str = r#"{"total_bytes":0,"total_count":0,"categories":[],"channel_bytes":{},"channel_counts":{},"cleanup_candidate_ids":[]}"#;

    let Ok(arr) = serde_json::from_str::<serde_json::Value>(recordings_json) else {
        return EMPTY.to_string();
    };
    let Some(items) = arr.as_array() else {
        return EMPTY.to_string();
    };

    let thirty_days_ms: i64 = 30 * 24 * 60 * 60 * 1000;
    let cutoff_ms = now_ms - thirty_days_ms;

    let mut total_bytes: i64 = 0;
    // category label → (count, bytes)
    let mut category_map: HashMap<String, (i64, i64)> = HashMap::new();
    // channel → bytes (completed only)
    let mut channel_bytes: HashMap<String, i64> = HashMap::new();
    // channel → count (completed only)
    let mut channel_counts: HashMap<String, i64> = HashMap::new();
    let mut cleanup_candidates: Vec<String> = Vec::new();

    for item in items {
        let id = item.get("id").and_then(|v| v.as_str()).unwrap_or("");
        let status = item.get("status").and_then(|v| v.as_str()).unwrap_or("");
        let channel = item
            .get("channel_name")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let file_bytes = item
            .get("file_size_bytes")
            .and_then(|v| v.as_i64())
            .unwrap_or(0);
        let end_time = item.get("end_time").and_then(|v| v.as_i64()).unwrap_or(0);

        total_bytes += file_bytes;

        let label = match status {
            "completed" => "Completed",
            "scheduled" => "Scheduled",
            "recording" => "Recording",
            "failed" => "Failed",
            other => other,
        };

        let entry = category_map.entry(label.to_string()).or_insert((0, 0));
        entry.0 += 1;
        entry.1 += file_bytes;

        if status == "completed" {
            *channel_bytes.entry(channel.to_string()).or_insert(0) += file_bytes;
            *channel_counts.entry(channel.to_string()).or_insert(0) += 1;

            if end_time < cutoff_ms && cleanup_candidates.len() < 10 {
                cleanup_candidates.push(id.to_string());
            }
        } else if status == "failed" && cleanup_candidates.len() < 10 {
            cleanup_candidates.push(id.to_string());
        }
    }

    // Build ordered categories list (non-empty groups only).
    let mut categories: Vec<serde_json::Value> = category_map
        .iter()
        .map(|(label, (count, bytes))| {
            serde_json::json!({
                "label": label,
                "count": count,
                "bytes": bytes,
            })
        })
        .collect();
    // Sort by label for deterministic output.
    categories.sort_by(|a, b| {
        a["label"]
            .as_str()
            .unwrap_or("")
            .cmp(b["label"].as_str().unwrap_or(""))
    });

    let result = serde_json::json!({
        "total_bytes": total_bytes,
        "total_count": items.len() as i64,
        "categories": categories,
        "channel_bytes": channel_bytes,
        "channel_counts": channel_counts,
        "cleanup_candidate_ids": cleanup_candidates,
    });

    serde_json::to_string(&result).unwrap_or_else(|_| EMPTY.to_string())
}

/// Filter recordings by a search query.
///
/// Input: JSON array of recording objects with:
///   `id`, `program_name`, `channel_name`, `start_time` (epoch ms).
///
/// If `query` is empty, returns the input array unchanged.
/// Otherwise performs a case-insensitive search across `program_name`,
/// `channel_name`, and the formatted date (`YYYY-MM-DD` of `start_time`).
///
/// Returns: JSON array of matching recording objects.
pub fn filter_recordings(recordings_json: &str, query: &str) -> String {
    use chrono::{DateTime, Utc};

    if query.is_empty() {
        return recordings_json.to_string();
    }

    let Ok(arr) = serde_json::from_str::<serde_json::Value>(recordings_json) else {
        return "[]".to_string();
    };
    let Some(items) = arr.as_array() else {
        return "[]".to_string();
    };

    let q = query.to_lowercase();

    let matched: Vec<&serde_json::Value> = items
        .iter()
        .filter(|item| {
            let program = item
                .get("program_name")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_lowercase();
            let channel = item
                .get("channel_name")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_lowercase();
            let start_ms = item.get("start_time").and_then(|v| v.as_i64()).unwrap_or(0);
            let date_str = DateTime::from_timestamp_millis(start_ms)
                .unwrap_or_else(|| DateTime::<Utc>::from_timestamp(0, 0).unwrap())
                .format("%Y-%m-%d")
                .to_string();

            program.contains(&q) || channel.contains(&q) || date_str.contains(&q)
        })
        .collect();

    serde_json::to_string(&matched).unwrap_or_else(|_| "[]".to_string())
}

/// Classify a filename's extension as "video", "audio", "subtitle", or "other".
///
/// Extension matching is case-insensitive. Files with no extension return "other".
pub fn classify_file_type(filename: &str) -> String {
    let ext = std::path::Path::new(filename)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase());

    match ext.as_deref() {
        Some(
            "mp4" | "mkv" | "avi" | "mov" | "ts" | "mpg" | "mpeg" | "m2ts" | "wmv" | "flv" | "webm"
            | "m4v",
        ) => "video".to_string(),
        Some("mp3" | "aac" | "flac" | "ogg" | "wav" | "opus" | "m4a" | "wma" | "ac3" | "eac3") => {
            "audio".to_string()
        }
        Some("srt" | "ass" | "ssa" | "vtt" | "sub" | "idx" | "sup" | "dfxp" | "ttml") => {
            "subtitle".to_string()
        }
        _ => "other".to_string(),
    }
}

/// Sort a JSON array of remote file objects.
///
/// Input: JSON array of objects with:
///   `name` (string), `is_directory` (bool), `modified_at` (epoch ms),
///   `size_bytes` (i64).
///
/// Directories are always sorted before non-directories.
///
/// `order` values: `"name_asc"`, `"name_desc"`, `"date_newest"`,
/// `"date_oldest"`, `"size_largest"`, `"size_smallest"`.
/// Unknown orders default to `"name_asc"`.
///
/// Returns: sorted JSON array.
pub fn sort_remote_files(files_json: &str, order: &str) -> String {
    let Ok(arr) = serde_json::from_str::<serde_json::Value>(files_json) else {
        return "[]".to_string();
    };
    let Some(items) = arr.as_array() else {
        return "[]".to_string();
    };

    let mut files: Vec<&serde_json::Value> = items.iter().collect();

    files.sort_by(|a, b| {
        let a_dir = a
            .get("is_directory")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let b_dir = b
            .get("is_directory")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        // Directories always come first.
        match (a_dir, b_dir) {
            (true, false) => return std::cmp::Ordering::Less,
            (false, true) => return std::cmp::Ordering::Greater,
            _ => {}
        }

        let a_name = a
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_lowercase();
        let b_name = b
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_lowercase();
        let a_date = a.get("modified_at").and_then(|v| v.as_i64()).unwrap_or(0);
        let b_date = b.get("modified_at").and_then(|v| v.as_i64()).unwrap_or(0);
        let a_size = a.get("size_bytes").and_then(|v| v.as_i64()).unwrap_or(0);
        let b_size = b.get("size_bytes").and_then(|v| v.as_i64()).unwrap_or(0);

        match order {
            "name_desc" => b_name.cmp(&a_name),
            "date_newest" => b_date.cmp(&a_date),
            "date_oldest" => a_date.cmp(&b_date),
            "size_largest" => b_size.cmp(&a_size),
            "size_smallest" => a_size.cmp(&b_size),
            // "name_asc" and any unknown order
            _ => a_name.cmp(&b_name),
        }
    });

    serde_json::to_string(&files).unwrap_or_else(|_| "[]".to_string())
}

// ── internal helpers ───────────────────────────────────

/// Combine a date with the time-of-day from a
/// `NaiveDateTime`.
fn combine_date_time(date: NaiveDate, time_source: NaiveDateTime) -> NaiveDateTime {
    date.and_hms_opt(
        time_source.time().hour(),
        time_source.time().minute(),
        time_source.time().second(),
    )
    .expect("valid HMS from existing NaiveDateTime")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algorithms::normalize::EPG_FORMAT;
    use chrono::NaiveDateTime;

    /// Helper: parse `"YYYY-MM-DD HH:MM:SS"` into a
    /// `NaiveDateTime`.
    fn dt(s: &str) -> NaiveDateTime {
        NaiveDateTime::parse_from_str(s, EPG_FORMAT).unwrap()
    }

    /// Helper: build a minimal `Recording`.
    #[allow(clippy::too_many_arguments)]
    fn make_recording(
        id: &str,
        channel: &str,
        program: &str,
        start: &str,
        end: &str,
        status: &str,
        is_recurring: bool,
        recur_days: i32,
    ) -> Recording {
        Recording {
            id: id.to_string(),
            channel_id: None,
            channel_name: channel.to_string(),
            channel_logo_url: None,
            program_name: program.to_string(),
            stream_url: None,
            start_time: dt(start),
            end_time: dt(end),
            status: status.to_string(),
            file_path: None,
            file_size_bytes: None,
            is_recurring,
            recur_days,
            owner_profile_id: None,
            is_shared: true,
            remote_backend_id: None,
            remote_path: None,
        }
    }

    // ── expand_recurring_recordings ────────────────────

    #[test]
    fn expand_recurring_mon_wed_fri() {
        // Mon=bit0, Wed=bit2, Fri=bit4 → 0b10101 = 21
        let rec = make_recording(
            "r1",
            "BBC One",
            "News",
            // Time-of-day: 20:00–21:00
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            true,
            21, // Mon + Wed + Fri
        );

        // "now" is Monday 2026-02-16 at 10:00.
        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[rec], now);

        // 7-day window: Mon 16 – Sun 22 Feb 2026.
        // Mon 16 Feb: bit0 ✓  (20:00 > 10:00 → future)
        // Tue 17 Feb: bit1 ✗
        // Wed 18 Feb: bit2 ✓
        // Thu 19 Feb: bit3 ✗
        // Fri 20 Feb: bit4 ✓
        // Sat 21 Feb: bit5 ✗
        // Sun 22 Feb: bit6 ✗
        assert_eq!(instances.len(), 3);
        assert_eq!(instances[0].start_time, dt("2026-02-16 20:00:00"),);
        assert_eq!(instances[1].start_time, dt("2026-02-18 20:00:00"),);
        assert_eq!(instances[2].start_time, dt("2026-02-20 20:00:00"),);
    }

    #[test]
    fn expand_skips_past_instances() {
        // Every day (all bits: 0b1111111 = 127).
        let rec = make_recording(
            "r1",
            "CH",
            "Show",
            "2026-02-16 08:00:00",
            "2026-02-16 09:00:00",
            "scheduled",
            true,
            127,
        );

        // "now" is Mon 16 Feb at 09:30 — today's
        // instance ended at 09:00, should be skipped.
        let now = dt("2026-02-16 09:30:00");
        let instances = expand_recurring_recordings(&[rec], now);

        // Mon skipped (ended), Tue–Sun = 6 instances.
        assert_eq!(instances.len(), 6);
        assert_eq!(instances[0].start_time, dt("2026-02-17 08:00:00"),);
    }

    #[test]
    fn expand_skips_existing_instances() {
        // Recurring: Mon + Tue (bits 0+1 = 3).
        let recurring = make_recording(
            "r1",
            "CH",
            "Show",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            true,
            3,
        );
        // Existing non-recurring instance for Monday.
        let existing = make_recording(
            "e1",
            "CH",
            "Show",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[recurring, existing], now);

        // Monday already exists → only Tuesday generated.
        assert_eq!(instances.len(), 1);
        assert_eq!(instances[0].start_time, dt("2026-02-17 20:00:00"),);
    }

    #[test]
    fn expand_skips_non_recurring() {
        let rec = make_recording(
            "r1",
            "CH",
            "Show",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false, // not recurring
            0,
        );

        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[rec], now);
        assert!(instances.is_empty());
    }

    // ── detect_recording_conflict ──────────────────────

    #[test]
    fn conflict_overlapping_same_channel() {
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "BBC One",
            dt("2026-02-16 20:30:00"),
            dt("2026-02-16 21:30:00"),
        );
        assert!(has_conflict);
    }

    #[test]
    fn no_conflict_non_overlapping() {
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "BBC One",
            dt("2026-02-16 21:00:00"),
            dt("2026-02-16 22:00:00"),
        );
        assert!(!has_conflict);
    }

    #[test]
    fn no_conflict_different_channel() {
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "CNN",
            dt("2026-02-16 20:00:00"),
            dt("2026-02-16 21:00:00"),
        );
        assert!(!has_conflict);
    }

    #[test]
    fn conflict_excludes_self() {
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        // Same time, same channel, but excluded by ID.
        let has_conflict = detect_recording_conflict(
            &[existing],
            Some("r1"),
            "BBC One",
            dt("2026-02-16 20:00:00"),
            dt("2026-02-16 21:00:00"),
        );
        assert!(!has_conflict);
    }

    // ── sanitize_filename ──────────────────────────────

    #[test]
    fn sanitize_replaces_special_chars() {
        let result = sanitize_filename("News: Live! (2026)");
        assert_eq!(result, "News_ Live_ _2026_");
    }

    #[test]
    fn sanitize_keeps_alphanumeric_and_hyphens() {
        let result = sanitize_filename("My-Show 2026_ep01");
        assert_eq!(result, "My-Show 2026_ep01");
    }

    // ── find_recordings_to_start ───────────────────────

    #[test]
    fn finds_scheduled_within_window() {
        let recs = vec![
            make_recording(
                "r1",
                "CH",
                "Show A",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "scheduled",
                false,
                0,
            ),
            make_recording(
                "r2",
                "CH",
                "Show B",
                "2026-02-16 22:00:00",
                "2026-02-16 23:00:00",
                "scheduled",
                false,
                0,
            ),
            make_recording(
                "r3",
                "CH",
                "Show C",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "recording",
                false,
                0,
            ),
        ];

        let now = dt("2026-02-16 20:30:00");
        let ids = find_recordings_to_start(&recs, now);

        // r1: scheduled + in window → yes
        // r2: scheduled but future → no
        // r3: recording (not scheduled) → no
        assert_eq!(ids, vec!["r1".to_string()]);
    }

    #[test]
    fn finds_nothing_when_all_past() {
        let recs = vec![make_recording(
            "r1",
            "CH",
            "Show",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        )];

        let now = dt("2026-02-16 22:00:00");
        let ids = find_recordings_to_start(&recs, now);
        assert!(ids.is_empty());
    }

    // ── Recurring: every-day bitmask ────────────────

    #[test]
    fn expand_every_day_bitmask() {
        // All 7 bits set: 0b1111111 = 127.
        let rec = make_recording(
            "r1",
            "CH",
            "Daily",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            true,
            127,
        );

        // Now is Mon 16 Feb at 10:00 — all 7 days'
        // 20:00 instances are in the future.
        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[rec], now);
        assert_eq!(instances.len(), 7);

        // Verify each day has an instance.
        for (i, inst) in instances.iter().enumerate() {
            let expected_day = 16 + i as u32;
            assert_eq!(inst.start_time.date().day(), expected_day,);
        }
    }

    // ── Recurring: weekday-only bitmask ─────────────

    #[test]
    fn expand_weekday_only_bitmask() {
        // Mon–Fri: bits 0–4 = 0b0011111 = 31.
        let rec = make_recording(
            "r1",
            "CH",
            "Weekday",
            "2026-02-16 18:00:00",
            "2026-02-16 19:00:00",
            "scheduled",
            true,
            31,
        );

        // Mon 16 Feb at 10:00.
        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[rec], now);

        // Mon 16, Tue 17, Wed 18, Thu 19, Fri 20 = 5.
        // Sat 21, Sun 22 are excluded.
        assert_eq!(instances.len(), 5);
        // Verify Saturday/Sunday are absent.
        for inst in &instances {
            let wd = inst.start_time.date().weekday().num_days_from_monday();
            assert!(wd < 5, "Weekday only — got {wd}");
        }
    }

    // ── Recurring: single-day bitmask ───────────────

    #[test]
    fn expand_single_day_sunday_only() {
        // Sunday = bit 6 = 64.
        let rec = make_recording(
            "r1",
            "CH",
            "Sunday Show",
            "2026-02-16 12:00:00",
            "2026-02-16 13:00:00",
            "scheduled",
            true,
            64,
        );

        // Mon 16 Feb at 10:00, 7-day window → Sun 22.
        let now = dt("2026-02-16 10:00:00");
        let instances = expand_recurring_recordings(&[rec], now);

        assert_eq!(instances.len(), 1);
        // Sun 22 Feb 2026.
        assert_eq!(instances[0].start_time, dt("2026-02-22 12:00:00"),);
    }

    // ── Conflict: adjacent non-overlapping ──────────

    #[test]
    fn no_conflict_adjacent_time_slots() {
        // Existing: 20:00–21:00.
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        // Candidate starts exactly when existing ends.
        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "BBC One",
            dt("2026-02-16 21:00:00"),
            dt("2026-02-16 22:00:00"),
        );
        assert!(!has_conflict, "Adjacent slots should not conflict",);
    }

    // ── Conflict: exact same time slot ──────────────

    #[test]
    fn conflict_exact_same_time_slot() {
        let existing = make_recording(
            "r1",
            "BBC One",
            "News",
            "2026-02-16 20:00:00",
            "2026-02-16 21:00:00",
            "scheduled",
            false,
            0,
        );

        // Candidate has identical start and end.
        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "BBC One",
            dt("2026-02-16 20:00:00"),
            dt("2026-02-16 21:00:00"),
        );
        assert!(has_conflict, "Identical time slots must conflict",);
    }

    // ── Conflict: nested recording ──────────────────

    #[test]
    fn conflict_nested_recording_inside_another() {
        // Existing: 19:00–22:00.
        let existing = make_recording(
            "r1",
            "BBC One",
            "Movie",
            "2026-02-16 19:00:00",
            "2026-02-16 22:00:00",
            "scheduled",
            false,
            0,
        );

        // Candidate: 20:00–21:00, fully inside.
        let has_conflict = detect_recording_conflict(
            &[existing],
            None,
            "BBC One",
            dt("2026-02-16 20:00:00"),
            dt("2026-02-16 21:00:00"),
        );
        assert!(has_conflict, "Nested recording must conflict",);
    }

    // ── Sanitize: unicode characters ────────────────

    #[test]
    fn sanitize_unicode_word_chars_preserved() {
        // Rust regex \w matches Unicode word chars by
        // default, so accented letters and CJK ideographs
        // are kept (they are Unicode \p{Alphabetic}).
        let result = sanitize_filename("Café résumé 日本語");
        assert_eq!(result, "Café résumé 日本語");
    }

    #[test]
    fn sanitize_unicode_symbols_replaced() {
        // Symbols like ™, ©, € are NOT word chars.
        let result = sanitize_filename("Show™ ©2026 €9.99");
        assert!(!result.contains('™'));
        assert!(!result.contains('©'));
        assert!(!result.contains('€'));
        assert_eq!(result, "Show_ _2026 _9_99");
    }

    // ── Sanitize: path separators ───────────────────

    #[test]
    fn sanitize_path_separators() {
        let result = sanitize_filename("path/to\\file<name>.ts");
        // /, \, <, > are all non-word → replaced.
        assert!(!result.contains('/'));
        assert!(!result.contains('\\'));
        assert!(!result.contains('<'));
        assert!(!result.contains('>'));
        assert_eq!(result, "path_to_file_name__ts",);
    }

    // ── Find recordings: none ready ─────────────────

    #[test]
    fn find_recordings_none_ready() {
        let recs = vec![
            // Future — not yet started.
            make_recording(
                "r1",
                "CH",
                "Future",
                "2026-02-16 22:00:00",
                "2026-02-16 23:00:00",
                "scheduled",
                false,
                0,
            ),
            // Past — already ended.
            make_recording(
                "r2",
                "CH",
                "Past",
                "2026-02-16 18:00:00",
                "2026-02-16 19:00:00",
                "scheduled",
                false,
                0,
            ),
            // Current but already recording.
            make_recording(
                "r3",
                "CH",
                "Active",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "recording",
                false,
                0,
            ),
        ];

        let now = dt("2026-02-16 20:30:00");
        let ids = find_recordings_to_start(&recs, now);
        assert!(ids.is_empty(), "No scheduled recordings in current window",);
    }

    // ── get_recordings_to_start (JSON variant) ──────

    #[test]
    fn get_recordings_to_start_empty_returns_empty_array() {
        let result = get_recordings_to_start("[]", 1_000_000);
        let ids: Vec<String> = serde_json::from_str(&result).unwrap();
        assert!(ids.is_empty());
    }

    #[test]
    fn get_recordings_to_start_one_in_window_returns_id() {
        let json = r#"[{
            "id": "r1",
            "status": "scheduled",
            "startTime": 900000,
            "endTime": 1100000
        }]"#;
        let result = get_recordings_to_start(json, 1_000_000);
        let ids: Vec<String> = serde_json::from_str(&result).unwrap();
        assert_eq!(ids, vec!["r1"]);
    }

    #[test]
    fn get_recordings_to_start_not_yet_started_returns_empty() {
        // startTime > now_ms → not started yet.
        let json = r#"[{
            "id": "r1",
            "status": "scheduled",
            "startTime": 2000000,
            "endTime": 3000000
        }]"#;
        let result = get_recordings_to_start(json, 1_000_000);
        let ids: Vec<String> = serde_json::from_str(&result).unwrap();
        assert!(ids.is_empty());
    }

    #[test]
    fn get_recordings_to_start_already_ended_returns_empty() {
        // endTime <= now_ms → already ended.
        let json = r#"[{
            "id": "r1",
            "status": "scheduled",
            "startTime": 500000,
            "endTime": 800000
        }]"#;
        let result = get_recordings_to_start(json, 1_000_000);
        let ids: Vec<String> = serde_json::from_str(&result).unwrap();
        assert!(ids.is_empty());
    }

    #[test]
    fn get_recordings_to_start_only_scheduled_returned() {
        // Mix of statuses — only "scheduled" qualifies.
        let json = r#"[
            {"id": "r1", "status": "scheduled",  "startTime": 900000,  "endTime": 1100000},
            {"id": "r2", "status": "recording",  "startTime": 900000,  "endTime": 1100000},
            {"id": "r3", "status": "completed",  "startTime": 900000,  "endTime": 1100000}
        ]"#;
        let result = get_recordings_to_start(json, 1_000_000);
        let ids: Vec<String> = serde_json::from_str(&result).unwrap();
        assert_eq!(ids, vec!["r1"]);
    }

    #[test]
    fn get_recordings_to_start_multiple_in_window_all_returned() {
        // Multiple scheduled recordings in the current window.
        let json = r#"[
            {"id": "r1", "status": "scheduled", "startTime": 800000, "endTime": 1200000},
            {"id": "r2", "status": "scheduled", "startTime": 850000, "endTime": 1300000},
            {"id": "r3", "status": "scheduled", "startTime": 1100000, "endTime": 1500000}
        ]"#;
        let result = get_recordings_to_start(json, 1_000_000);
        let mut ids: Vec<String> = serde_json::from_str(&result).unwrap();
        ids.sort();
        assert_eq!(ids, vec!["r1", "r2"]);
    }

    // ── Find recordings: multiple simultaneous ──────

    #[test]
    fn find_recordings_multiple_simultaneous() {
        let recs = vec![
            make_recording(
                "r1",
                "BBC One",
                "News",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "scheduled",
                false,
                0,
            ),
            make_recording(
                "r2",
                "CNN",
                "Breaking",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "scheduled",
                false,
                0,
            ),
            make_recording(
                "r3",
                "ITV",
                "Drama",
                "2026-02-16 20:00:00",
                "2026-02-16 21:00:00",
                "scheduled",
                false,
                0,
            ),
        ];

        let now = dt("2026-02-16 20:30:00");
        let ids = find_recordings_to_start(&recs, now);
        assert_eq!(ids.len(), 3);
        assert!(ids.contains(&"r1".to_string()));
        assert!(ids.contains(&"r2".to_string()));
        assert!(ids.contains(&"r3".to_string()));
    }

    // ── compute_storage_breakdown ───────────────────

    #[test]
    fn storage_breakdown_empty_input_returns_zeroes() {
        let result = compute_storage_breakdown("[]", 1_000_000_000);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        assert_eq!(v["total_bytes"], 0);
        assert_eq!(v["total_count"], 0);
        assert!(v["categories"].as_array().unwrap().is_empty());
    }

    #[test]
    fn storage_breakdown_multiple_statuses_aggregated() {
        let json = r#"[
            {"id":"r1","status":"completed","channel_name":"BBC","file_size_bytes":1000,"end_time":0},
            {"id":"r2","status":"completed","channel_name":"CNN","file_size_bytes":2000,"end_time":0},
            {"id":"r3","status":"recording","channel_name":"ITV","file_size_bytes":500,"end_time":0},
            {"id":"r4","status":"scheduled","channel_name":"SKY","file_size_bytes":null,"end_time":0},
            {"id":"r5","status":"failed","channel_name":"BBC","file_size_bytes":0,"end_time":0}
        ]"#;
        let result = compute_storage_breakdown(json, 9_999_999_999_999);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        assert_eq!(v["total_bytes"], 3500);
        assert_eq!(v["total_count"], 5);

        let cats = v["categories"].as_array().unwrap();
        // Completed, Failed, Recording, Scheduled are all present.
        assert_eq!(cats.len(), 4);
    }

    #[test]
    fn storage_breakdown_per_channel_aggregation_completed_only() {
        let json = r#"[
            {"id":"r1","status":"completed","channel_name":"BBC","file_size_bytes":1000,"end_time":0},
            {"id":"r2","status":"completed","channel_name":"BBC","file_size_bytes":2000,"end_time":0},
            {"id":"r3","status":"recording","channel_name":"BBC","file_size_bytes":500,"end_time":0}
        ]"#;
        // now_ms far in future so no cleanup candidates.
        let result = compute_storage_breakdown(json, 9_999_999_999_999);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        // Only completed recordings count for channel stats.
        assert_eq!(v["channel_bytes"]["BBC"], 3000);
        assert_eq!(v["channel_counts"]["BBC"], 2);
    }

    #[test]
    fn storage_breakdown_cleanup_candidates_threshold_30_days() {
        // 1 day = 86_400_000 ms.
        // now = 40 days, cutoff = now - 30 days = 10 days.
        let forty_days_ms: i64 = 40 * 86_400_000;
        // 5 days < cutoff (10 days) → candidate.
        let five_days_ms: i64 = 5 * 86_400_000;
        // 20 days > cutoff (10 days) → not candidate.
        let twenty_days_ms: i64 = 20 * 86_400_000;

        let json = format!(
            r#"[
                {{"id":"old","status":"completed","channel_name":"CH","file_size_bytes":0,"end_time":{five_days_ms}}},
                {{"id":"new","status":"completed","channel_name":"CH","file_size_bytes":0,"end_time":{twenty_days_ms}}}
            ]"#
        );
        let result = compute_storage_breakdown(&json, forty_days_ms);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let candidates = v["cleanup_candidate_ids"].as_array().unwrap();
        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0], "old");
    }

    #[test]
    fn storage_breakdown_failed_recordings_are_cleanup_candidates() {
        let json = r#"[
            {"id":"f1","status":"failed","channel_name":"BBC","file_size_bytes":0,"end_time":0},
            {"id":"f2","status":"failed","channel_name":"CNN","file_size_bytes":0,"end_time":0}
        ]"#;
        let result = compute_storage_breakdown(json, 9_999_999_999_999);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let candidates = v["cleanup_candidate_ids"].as_array().unwrap();
        assert_eq!(candidates.len(), 2);
    }

    #[test]
    fn storage_breakdown_cleanup_candidates_capped_at_10() {
        // 15 failed recordings — only 10 should appear in candidates.
        let items: Vec<String> = (0..15)
            .map(|i| {
                format!(
                    r#"{{"id":"f{i}","status":"failed","channel_name":"CH","file_size_bytes":0,"end_time":0}}"#
                )
            })
            .collect();
        let json = format!("[{}]", items.join(","));
        let result = compute_storage_breakdown(&json, 9_999_999_999_999);
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        assert_eq!(v["cleanup_candidate_ids"].as_array().unwrap().len(), 10);
    }

    // ── filter_recordings ────────────────────────────

    #[test]
    fn filter_recordings_empty_query_returns_input_unchanged() {
        let json = r#"[{"id":"r1","program_name":"News","channel_name":"BBC","start_time":0}]"#;
        let result = filter_recordings(json, "");
        assert_eq!(result, json);
    }

    #[test]
    fn filter_recordings_match_by_program_name() {
        let json = r#"[
            {"id":"r1","program_name":"Evening News","channel_name":"BBC","start_time":0},
            {"id":"r2","program_name":"Sport Live","channel_name":"BBC","start_time":0}
        ]"#;
        let result = filter_recordings(json, "news");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr.len(), 1);
        assert_eq!(arr[0]["id"], "r1");
    }

    #[test]
    fn filter_recordings_match_by_channel_name() {
        let json = r#"[
            {"id":"r1","program_name":"Show A","channel_name":"BBC One","start_time":0},
            {"id":"r2","program_name":"Show B","channel_name":"CNN","start_time":0}
        ]"#;
        let result = filter_recordings(json, "bbc");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr.len(), 1);
        assert_eq!(arr[0]["id"], "r1");
    }

    #[test]
    fn filter_recordings_match_by_formatted_date() {
        // epoch 0 ms → 1970-01-01; 1000000000000 ms → 2001-09-09.
        let json = r#"[
            {"id":"r1","program_name":"Show","channel_name":"CH","start_time":0},
            {"id":"r2","program_name":"Other","channel_name":"CH","start_time":1000000000000}
        ]"#;
        let result = filter_recordings(json, "1970-01-01");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr.len(), 1);
        assert_eq!(arr[0]["id"], "r1");
    }

    #[test]
    fn filter_recordings_no_match_returns_empty_array() {
        let json = r#"[
            {"id":"r1","program_name":"Evening News","channel_name":"BBC","start_time":0}
        ]"#;
        let result = filter_recordings(json, "zzznomatch");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        assert!(v.as_array().unwrap().is_empty());
    }

    // ── classify_file_type ───────────────────────────

    #[test]
    fn classify_video_extensions() {
        let exts = [
            "mp4", "mkv", "avi", "mov", "ts", "mpg", "mpeg", "m2ts", "wmv", "flv", "webm", "m4v",
        ];
        for ext in &exts {
            let filename = format!("recording.{ext}");
            assert_eq!(classify_file_type(&filename), "video", "failed for .{ext}");
        }
    }

    #[test]
    fn classify_audio_extensions() {
        let exts = [
            "mp3", "aac", "flac", "ogg", "wav", "opus", "m4a", "wma", "ac3", "eac3",
        ];
        for ext in &exts {
            let filename = format!("track.{ext}");
            assert_eq!(classify_file_type(&filename), "audio", "failed for .{ext}");
        }
    }

    #[test]
    fn classify_subtitle_extensions() {
        let exts = [
            "srt", "ass", "ssa", "vtt", "sub", "idx", "sup", "dfxp", "ttml",
        ];
        for ext in &exts {
            let filename = format!("subtitles.{ext}");
            assert_eq!(
                classify_file_type(&filename),
                "subtitle",
                "failed for .{ext}"
            );
        }
    }

    #[test]
    fn classify_unknown_extension_returns_other() {
        assert_eq!(classify_file_type("document.pdf"), "other");
        assert_eq!(classify_file_type("archive.zip"), "other");
    }

    #[test]
    fn classify_no_extension_returns_other() {
        assert_eq!(classify_file_type("noextension"), "other");
        assert_eq!(classify_file_type(""), "other");
    }

    #[test]
    fn classify_extension_case_insensitive() {
        assert_eq!(classify_file_type("video.MP4"), "video");
        assert_eq!(classify_file_type("audio.AAC"), "audio");
        assert_eq!(classify_file_type("sub.SRT"), "subtitle");
    }

    // ── sort_remote_files ────────────────────────────

    #[test]
    fn sort_remote_files_directories_always_first() {
        let json = r#"[
            {"name":"z_file.mp4","is_directory":false,"modified_at":0,"size_bytes":100},
            {"name":"a_dir","is_directory":true,"modified_at":0,"size_bytes":0},
            {"name":"b_file.ts","is_directory":false,"modified_at":0,"size_bytes":200}
        ]"#;
        let result = sort_remote_files(json, "name_asc");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "a_dir");
        assert_eq!(arr[0]["is_directory"], true);
    }

    #[test]
    fn sort_remote_files_name_asc() {
        let json = r#"[
            {"name":"Charlie.mp4","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"Alpha.mp4","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"Beta.mp4","is_directory":false,"modified_at":0,"size_bytes":0}
        ]"#;
        let result = sort_remote_files(json, "name_asc");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "Alpha.mp4");
        assert_eq!(arr[1]["name"], "Beta.mp4");
        assert_eq!(arr[2]["name"], "Charlie.mp4");
    }

    #[test]
    fn sort_remote_files_name_desc() {
        let json = r#"[
            {"name":"Alpha.mp4","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"Charlie.mp4","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"Beta.mp4","is_directory":false,"modified_at":0,"size_bytes":0}
        ]"#;
        let result = sort_remote_files(json, "name_desc");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "Charlie.mp4");
        assert_eq!(arr[1]["name"], "Beta.mp4");
        assert_eq!(arr[2]["name"], "Alpha.mp4");
    }

    #[test]
    fn sort_remote_files_date_newest() {
        let json = r#"[
            {"name":"old.mp4","is_directory":false,"modified_at":1000,"size_bytes":0},
            {"name":"new.mp4","is_directory":false,"modified_at":3000,"size_bytes":0},
            {"name":"mid.mp4","is_directory":false,"modified_at":2000,"size_bytes":0}
        ]"#;
        let result = sort_remote_files(json, "date_newest");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "new.mp4");
        assert_eq!(arr[1]["name"], "mid.mp4");
        assert_eq!(arr[2]["name"], "old.mp4");
    }

    #[test]
    fn sort_remote_files_date_oldest() {
        let json = r#"[
            {"name":"new.mp4","is_directory":false,"modified_at":3000,"size_bytes":0},
            {"name":"old.mp4","is_directory":false,"modified_at":1000,"size_bytes":0},
            {"name":"mid.mp4","is_directory":false,"modified_at":2000,"size_bytes":0}
        ]"#;
        let result = sort_remote_files(json, "date_oldest");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "old.mp4");
        assert_eq!(arr[2]["name"], "new.mp4");
    }

    #[test]
    fn sort_remote_files_size_largest() {
        let json = r#"[
            {"name":"small.mp4","is_directory":false,"modified_at":0,"size_bytes":100},
            {"name":"large.mp4","is_directory":false,"modified_at":0,"size_bytes":9999},
            {"name":"medium.mp4","is_directory":false,"modified_at":0,"size_bytes":500}
        ]"#;
        let result = sort_remote_files(json, "size_largest");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "large.mp4");
        assert_eq!(arr[2]["name"], "small.mp4");
    }

    #[test]
    fn sort_remote_files_size_smallest() {
        let json = r#"[
            {"name":"large.mp4","is_directory":false,"modified_at":0,"size_bytes":9999},
            {"name":"small.mp4","is_directory":false,"modified_at":0,"size_bytes":100},
            {"name":"medium.mp4","is_directory":false,"modified_at":0,"size_bytes":500}
        ]"#;
        let result = sort_remote_files(json, "size_smallest");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        assert_eq!(arr[0]["name"], "small.mp4");
        assert_eq!(arr[2]["name"], "large.mp4");
    }

    #[test]
    fn sort_remote_files_mixed_dirs_and_files_dirs_first() {
        let json = r#"[
            {"name":"z_file.ts","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"b_dir","is_directory":true,"modified_at":0,"size_bytes":0},
            {"name":"a_file.mp4","is_directory":false,"modified_at":0,"size_bytes":0},
            {"name":"a_dir","is_directory":true,"modified_at":0,"size_bytes":0}
        ]"#;
        let result = sort_remote_files(json, "name_asc");
        let v: serde_json::Value = serde_json::from_str(&result).unwrap();
        let arr = v.as_array().unwrap();
        // Dirs first: a_dir, b_dir; then files: a_file.mp4, z_file.ts
        assert_eq!(arr[0]["name"], "a_dir");
        assert_eq!(arr[1]["name"], "b_dir");
        assert_eq!(arr[2]["name"], "a_file.mp4");
        assert_eq!(arr[3]["name"], "z_file.ts");
    }
}
